#!/bin/bash

## Test a mesh and configuration (e.g. quadrature rules) for point
## source boundary conditions by comparing exact and computed
## solutions on mesh and/or in field

mesh=sphere.bem
field=sphere-field.bem
source=source-laplace.fn
config=sphere-laplace.cfg
gconfig=sphere-laplace-gradient.cfg
gradient=gradient-laplace.fn

bem3d-assemble -C ${config} -i ${mesh} -o laplace.mtx
bem3d-function -E 2 -i ${mesh} -F ${source} -o bc-laplace.dat
bem3d-solve -C ${config} -d bc-laplace.dat -m laplace.mtx \
	    -o potential.dat

bem3d-function -E 2 -i ${mesh} -F ${source} -o ref-laplace.dat
bem3d-function -E 2 -i ${mesh} -F compare-real.fn \
	       -d ref-laplace.dat -e potential.dat -o check.dat

bem3d-field -C ${config} -d potential.dat -i ${mesh} \
	    -o field.dat -s ${field} 
bem3d-function -E 2 -i ${field} -F ${source} -o field-laplace.dat
bem3d-function -E 2 -i ${field} -F compare-real.fn \
	       -d field-laplace.dat -e field.dat -o check-field.dat

bem3d-field -C ${gconfig} -d potential.dat -i ${mesh} \
	    -o gradient.dat -s ${field} 
bem3d-function -E 4 -i ${field} -F ${gradient} -o gradient-laplace.dat
bem3d-function -E 4 -i ${field} -F compare-real-vector.fn \
	       -d gradient-laplace.dat -e gradient.dat -o check-gradient.dat
