Configuring BEM3D
Enumerations
enum BEM3DSolver
Functions
 BEM3DConfiguration * bem3d_configuration_new ()
gint bem3d_configuration_set (BEM3DConfiguration *c, gpointer k)
gint bem3d_configuration_read (BEM3DConfiguration *c, gchar *file)
gint bem3d_configuration_init (void)
gint bem3d_configuration_add_identifier (const gchar *id, gpointer v)
gchar * bem3d_configuration_identifier_from_pointer (gpointer v)
gpointer bem3d_configuration_pointer_from_identifier (const gchar *id)
gint bem3d_configuration_write_generic (gboolean write_descriptions, gint line_width, gchar *prefix, gchar *comment, FILE *f)
Detailed Description
BEM3D codes can be configured at run-time using glib key files and the following functions.
Enumeration Type Documentation
BEM3DSolver
enum BEM3DSolver
Solver selection to choose between, for example, direct and Fast Multipole Method in configuration files.
Function Documentation
bem3d_configuration_add_identifier()
gint bem3d_configuration_add_identifier (const gchar * id, gpointer v)
Add an identifier to the configuration data. This allows the identifier to be recognized by the bem3d_configuration_ functions. For example,
bem3d_configuration_add_identifier(`bem3d_quadrature_polar`, bem3d_quadrature_rule_polar) ;
adds the identifier `bem3d_quadrature_polar` which refers to the quadrature function of the same name, allowing a key file to contain a configuration line of the form
quadrature[1] = bem3d_quadrature_polar(0.0,16,16)
Parameters
id name of identifier;
description text string describing the variable (e.g. to be used as a comment in a configuration file)
v a pointer to the identified object
Returns
::BEM3D_SUCCESS on success
bem3d_configuration_identifier_from_pointer()
gchar* bem3d_configuration_identifier_from_pointer (gpointer v)
Find the identifier associated with a given object, set using bem3d_configuration_add_identifier
Parameters
v pointer to an object
Returns
the identifier associated with v
bem3d_configuration_init()
gint bem3d_configuration_init (void)
Initialize internal data for BEM3DConfiguration. This function should be called before any configurations are set or used, i.e. at the start of any program.
Returns
::BEM3D_SUCCESS on success
bem3d_configuration_new()
 BEM3DConfiguration* bem3d_configuration_new (void)
Allocate a new BEM3DConfiguration, filled with default settings (Laplace, bem3d_quadrature_rule_default, direct solver).
Returns
newly allocated BEM3DConfiguration
References bem3d_greens_func_laplace(), bem3d_greens_function_func, bem3d_greens_function_is_real, bem3d_quadrature_rule_default(), and bem3d_quadrature_selector_default().
bem3d_configuration_pointer_from_identifier()
gpointer bem3d_configuration_pointer_from_identifier (const gchar * id)
Look up the object associated with a given configuration identifier, set using bem3d_configuration_add_identifier
Parameters
id identifier used in configuration settings;
Returns
a pointer to the object associated with id
bem3d_configuration_read()
gint bem3d_configuration_read (BEM3DConfiguration * c, gchar * file)
Read BEM3D configuration data from a key file.
Parameters
c a BEM3DConfiguration
file a GLIB format key file containing configuration data
Returns
::BEM3D_SUCCESS on success.
References bem3d_configuration_set().
bem3d_configuration_set()
gint bem3d_configuration_set (BEM3DConfiguration * c, gpointer k)
Set fields of a BEM3DConfiguration from a key file, overwriting previous settings. Settings are read from the `BEM3D` group of the file, to allow codes to keep all their settings in one place. Values not in the `BEM3D` group are ignored.
Parameters
c a BEM3DConfiguration;
k a GKeyFile containing settings for c.
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_configuration_read().
bem3d_configuration_write_generic()
gint bem3d_configuration_write_generic (gboolean write_descriptions, gint line_width, gchar * prefix, gchar * comment, FILE * f)
Write generic configuration data containing all possible settings, which can be used as a template for a configuration file. Output is written in the form:
[Group name] prefix [setting] = [variable name] prefix [setting] = [variable name] prefix [setting] = [variable name]
Parameters
write_descriptions insert comment with description of variable before each line
line_width total number of characters per line in output, applied to lines of description only
prefix string to insert at start of each variable line, such as `#' to comment out entries
comment string to insert at start of descriptions, to comment out text
f output file stream
Returns
0 on success