Building elements
Data Structures
struct BEM3DElementBuildFunc
Functions
 BEM3DElement * bem3d_element_build_t0 (GtsEdge **e, GtsVertex **v)
 BEM3DElement * bem3d_element_build_t1 (GtsEdge **e, GtsVertex **v)
 BEM3DElement * bem3d_element_build_t2 (GtsEdge **e, GtsVertex **v)
 BEM3DElement * bem3d_element_build_t3 (GtsEdge **e, GtsVertex **v)
 BEM3DElement * bem3d_element_build_q1 (GtsEdge **e, GtsVertex **v)
 BEM3DElement * bem3d_element_build_q2 (GtsEdge **e, GtsVertex **v)
Detailed Description
BEM3D can handle a wide range of elements and some of them are built in to the main library. The BEMElement type contains the geometric and other information needed to perform calculations; the BEM3DElementBuildFunc type defines a function which takes as input the vertices of an element and returns the new element. In each case, the inputs are an array of GtsEdge's and an array of GtsVertex's which define the boundary of the element, with the exception of bem3d_element_build_t3 and bem3d_element_build_q2 which include an interior point in the centre of the element.
Function Documentation
bem3d_element_build_q1()
 BEM3DElement* bem3d_element_build_q1 (GtsEdge ** e, GtsVertex ** v)
Generate a first order quadrilateral element. The shape function for geometry and computation is bem3d_shfunc_q1.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new element
bem3d_element_build_q2()
 BEM3DElement* bem3d_element_build_q2 (GtsEdge ** e, GtsVertex ** v)
Generate a second order quadrilateral element, based on the GMSH nine point quad. The shape function for geometry and computation is bem3d_shfunc_q2.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new element
References bem3d_element_add_vertex(), bem3d_element_class(), bem3d_element_new(), bem3d_element_set_corner(), and bem3d_shfunc_q2().
bem3d_element_build_t0()
 BEM3DElement* bem3d_element_build_t0 (GtsEdge ** e, GtsVertex ** v)
Generate a zero order triangular element. The shape function for computation is bem3d_shfunc_t0 and for the geometry is bem3d_shfunc_t1.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new element
References bem3d_element_add_face(), bem3d_element_add_node(), bem3d_element_add_vertex(), bem3d_element_class(), bem3d_element_new(), bem3d_element_node_eta, bem3d_element_node_xi, bem3d_element_set_corner(), bem3d_element_vertex_eta, bem3d_element_vertex_xi, bem3d_shfunc_t0(), and bem3d_shfunc_t1().
bem3d_element_build_t1()
 BEM3DElement* bem3d_element_build_t1 (GtsEdge ** e, GtsVertex ** v)
Generate a first order triangular element. The shape function for geometry and computation is bem3d_shfunc_t1.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new BEM3DElement
bem3d_element_build_t2()
 BEM3DElement* bem3d_element_build_t2 (GtsEdge ** e, GtsVertex ** v)
Generate a second order triangular element. The shape function for geometry and computation is bem3d_shfunc_t2.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new element
References bem3d_element_class(), bem3d_element_new(), and bem3d_shfunc_t2().
bem3d_element_build_t3()
 BEM3DElement* bem3d_element_build_t3 (GtsEdge ** e, GtsVertex ** v)
Generate a third order triangular element. The shape function for geometry and computation is bem3d_shfunc_t3. If the tenth GtsVertex in v is NULL, the centre vertex is the centroid of the supplied vertices, otherwise v[9] is used.
Parameters
e array of GtsEdge around the outside of the element
v array of GtsVertex around the outside of the element
Returns
a pointer to the new element
References bem3d_element_add_face(), bem3d_element_add_vertex(), bem3d_element_class(), bem3d_element_new(), bem3d_element_set_corner(), bem3d_element_vertex_eta, bem3d_element_vertex_xi, and bem3d_shfunc_t3().