BEM3D elements
Macros
#define bem3d_element_face_number(e)
#define bem3d_element_vertex_number(e)
#define bem3d_element_node_number(e)
#define bem3d_element_corner_number(e)
#define bem3d_element_corner(e, i)
#define bem3d_element_corner_index(e, i)
#define bem3d_element_global_index(_e, _i)
#define bem3d_element_shape_func(e)
#define bem3d_element_node_func(e)
#define bem3d_element_node(e, i)
#define bem3d_element_node_xi(e, i)
#define bem3d_element_node_eta(e, i)
#define bem3d_element_vertex(e, i)
#define bem3d_element_vertex_xi(e, i)
#define bem3d_element_vertex_eta(e, i)
#define bem3d_element_face(e, i)
#define bem3d_element_moment_order(e)
#define bem3d_element_moment(e, m, n)
#define bem3d_element_has_parent_mesh(m, el)
Typedefs
typedef struct _BEM3DElement BEM3DElement
typedef struct _BEM3DElementClass BEM3DElementClass
Functions
 BEM3DElementClass * bem3d_element_class (void)
 BEM3DElement * bem3d_element_new (BEM3DElementClass *klass, gint nf, gint nv, gint nc, gint ns, BEM3DShapeFunc shf, BEM3DShapeFunc cpf)
gint bem3d_element_add_face (BEM3DElement *e, gpointer f, gint i)
gint bem3d_element_add_vertex (BEM3DElement *e, gpointer v, gint i)
gint bem3d_element_add_node (BEM3DElement *e, gpointer v, gint i)
gint bem3d_element_set_index (BEM3DElement *e, gint i, gint j)
gint bem3d_element_set_corner (BEM3DElement *e, gint i, gint j)
gint bem3d_element_write (BEM3DElement *e, GHashTable *v, GHashTable *t, FILE *f)
gint bem3d_element_find_vertex (BEM3DElement *e, GtsVertex *v)
gint bem3d_element_find_node (BEM3DElement *e, GtsVertex *v)
gdouble bem3d_element_area (BEM3DElement *e, gint ngp)
gint bem3d_element_position (BEM3DElement *e, gdouble *L, GtsPoint *q)
gdouble bem3d_element_jacobian (BEM3DElement *e, gdouble *dLds, gdouble *dLdt)
gint bem3d_element_normal (BEM3DElement *e, gdouble *dLds, gdouble *dLdt, GtsVector normal, gdouble *J)
gint bem3d_element_jacobian_matrix_normal (BEM3DElement *e, gdouble *dLds, gdouble *dLdt, GtsVector normal, gdouble *J, gdouble *Ji)
gint bem3d_element_assemble_equations (BEM3DElement *e, GtsPoint *x, BEM3DConfiguration *config, BEM3DParameters *gdata, GArray *G, GArray *dGdn)
gboolean bem3d_element_has_vertex (BEM3DElement *e, GtsVertex *v)
gboolean bem3d_element_has_node (BEM3DElement *e, GtsVertex *v)
GSList * bem3d_element_common_nodes (BEM3DElement *e1, BEM3DElement *e2)
GSList * bem3d_element_neighbours (BEM3DElement *el, BEM3DMesh *m)
 BEM3DElement * bem3d_element_from_node (BEM3DMesh *m, GtsVertex *v, gint i)
gint bem3d_element_index_nodes (BEM3DElement *e, BEM3DMesh *m, gint *n)
gint bem3d_element_local_vectors (BEM3DElement *e, gdouble dLds[], gdouble dLdt[], GtsVector u1, gdouble *h1, GtsVector u2, gdouble *h2)
GSList * bem3d_elements_common_edges (BEM3DElement *e1, BEM3DElement *e2)
gint bem3d_element_gradient_weights (BEM3DElement *e, gdouble xi, gdouble eta, gdouble *w)
gint bem3d_element_vertex_is_corner (BEM3DElement *e, GtsVertex *v)
gint bem3d_element_find_index (BEM3DElement *e, gint i)
GtsBBox * bem3d_element_bounding_box (GtsBBoxClass *klass, BEM3DElement *e)
GSList * bem3d_elements_from_vertices (BEM3DMesh *m, GtsVertex *v1, GtsVertex *v2)
gint bem3d_element_assemble_equations_direct (BEM3DElement *e, GtsPoint *x, gint ix, BEM3DConfiguration *config, BEM3DParameters *gdata, gdouble *a, gdouble *b)
gint bem3d_element_nearest_vertex (BEM3DElement *e, GtsPoint *p, gint *i, gdouble *R)
gboolean bem3d_element_point_inside (BEM3DElement *e, gdouble xi, gdouble eta)
gint bem3d_element_nearest_point (BEM3DElement *e, GtsPoint *x, gdouble *xi, gdouble *eta, gboolean constrain)
gint bem3d_element_edge_nearest_point (BEM3DElement *e, gint i, gint j, GtsPoint *x, gdouble *xi, gdouble *eta)
gint bem3d_element_boundary_nearest_point (BEM3DElement *e, GtsPoint *x, gdouble *xi, gdouble *eta)
Detailed Description
The definitions of the basic BEM3DElement and the functions for handling it. To see how to define new types of element, consult Building elements
Macro Definition Documentation
bem3d_element_corner
#define bem3d_element_corner(e, i)
Parameters
e a BEM3DElement
i index of a corner 0 < i < bem3d_element_corner_number(e)
Returns
the GtsVertex at the i th corner of e.
Referenced by bem3d_element_vertex_is_corner().
bem3d_element_corner_index
#define bem3d_element_corner_index(e, i)
Parameters
e a BEM3DElement
i index of a corner 0 < i < bem3d_element_corner_number(e)
Returns
the local index of the i th corner of e.
bem3d_element_corner_number
#define bem3d_element_corner_number(e)
Parameters
e a BEM3DElement
Returns
the number of corners on the element e
Referenced by bem3d_element_set_corner(), bem3d_element_vertex_is_corner(), bem3d_quadrature_rule_gauss(), bem3d_quadrature_rule_hayami(), bem3d_quadrature_rule_kw(), bem3d_quadrature_rule_polar(), bem3d_quadrature_rule_polar_hs(), and bem3d_quadrature_rule_wx().
bem3d_element_face
#define bem3d_element_face(e, i)
Parameters
e a BEM3DElement
i local index of a GtsFace on e
Returns
the i th GtsFace of e.
Referenced by bem3d_element_neighbours(), and bem3d_elements_common_edges().
bem3d_element_face_number
#define bem3d_element_face_number(e)
Parameters
e a BEM3DElement
Returns
the number of GtsFaces on the element e
Referenced by bem3d_element_add_face(), bem3d_element_neighbours(), and bem3d_elements_common_edges().
bem3d_element_global_index
#define bem3d_element_global_index(_e, _i)
Parameters
_e a BEM3DElement
_i local index of a collocation point
Returns
the global index of the i th collocation point of e.
Referenced by bem3d_element_assemble_equations_direct(), bem3d_element_find_index(), bem3d_element_from_node(), bem3d_element_radiation_point(), bem3d_mesh_add_element(), bem3d_mesh_index_from_node(), and bem3d_mesh_vertex_index_number().
bem3d_element_has_parent_mesh
#define bem3d_element_has_parent_mesh(m, el)
Parameters
m a BEM3DMesh
el a BEM3DElement
Returns
TRUE if el is an element of m, FALSE otherwise.
bem3d_element_moment
#define bem3d_element_moment(e, m, n)
Parameters
e a BEM3DElement
m order of $x$ in multipole moment;
n order of $y$ in multipole moment.
Returns
$I_{mn}$ for element e.
bem3d_element_moment_order
#define bem3d_element_moment_order(e)
Parameters
e a BEM3DElement
Returns
the order of the moments for element e.
Referenced by bem3d_element_new().
bem3d_element_node
#define bem3d_element_node(e, i)
Parameters
e a BEM3DElement
i local index of a collocation point on e
Returns
the GtsVertex of the i th node (collocation point) of e.
Referenced by bem3d_element_common_nodes(), bem3d_element_index_nodes(), bem3d_quadrature_rule_newman(), and bem3d_quadrature_rule_newman_gradient().
bem3d_element_node_eta
#define bem3d_element_node_eta(e, i)
Parameters
e a BEM3DElement
i local index of a node on e
Returns
the local coordinate $\eta$ of the i th node of e.
Referenced by bem3d_element_build_t0(), and bem3d_mesh_read().
bem3d_element_node_func
#define bem3d_element_node_func(e)
Parameters
e a BEM3DElement
Returns
the collocation BEM3DShapeFunc of e
Referenced by bem3d_element_assemble_equations(), bem3d_element_assemble_equations_direct(), and bem3d_element_radiation_point().
bem3d_element_node_number
#define bem3d_element_node_number(e)
Parameters
e a BEM3DElement
Returns
the number of nodes (collocation points) on the element e
Referenced by bem3d_element_add_node(), bem3d_element_area(), bem3d_element_assemble_equations(), bem3d_element_assemble_equations_direct(), bem3d_element_common_nodes(), bem3d_element_find_index(), bem3d_element_gradient_weights(), bem3d_element_has_node(), bem3d_element_index_nodes(), bem3d_element_radiation_point(), bem3d_element_set_index(), bem3d_mesh_add_element(), bem3d_quadrature_rule_newman(), bem3d_quadrature_rule_newman_gradient(), and bem3d_quadrature_rule_series().
bem3d_element_node_xi
#define bem3d_element_node_xi(e, i)
Parameters
e a BEM3DElement
i local index of a node on e
Returns
the local coordinate $\xi$ of the i th node of e.
Referenced by bem3d_element_build_t0(), and bem3d_mesh_read().
bem3d_element_shape_func
#define bem3d_element_shape_func(e)
Parameters
e a BEM3DElement
Returns
the geometric BEM3DShapeFunc of e
Referenced by bem3d_element_area(), bem3d_element_assemble_equations(), bem3d_element_assemble_equations_direct(), bem3d_element_boundary_nearest_point(), bem3d_element_gradient_weights(), bem3d_element_radiation_point(), and bem3d_node_normal().
bem3d_element_vertex
#define bem3d_element_vertex(e, i)
Parameters
e a BEM3DElement
i local index of a geometric point on e
Returns
the GtsVertex of the i th geometric point of e.
Referenced by bem3d_element_bounding_box(), bem3d_element_local_vectors(), and bem3d_quadrature_rule_series().
bem3d_element_vertex_eta
#define bem3d_element_vertex_eta(e, i)
Parameters
e a BEM3DElement
i local index of a collocation point on e
Returns
the local coordinate $\eta$ of the i th vertex of e.
Referenced by bem3d_element_build_t0(), bem3d_element_build_t3(), bem3d_element_nearest_point(), and bem3d_mesh_read().
bem3d_element_vertex_number
#define bem3d_element_vertex_number(e)
Parameters
e a BEM3DElement
Returns
the number of geometrical vertices on the element e
Referenced by bem3d_element_add_vertex(), bem3d_element_bounding_box(), bem3d_element_has_vertex(), bem3d_element_jacobian(), bem3d_element_jacobian_matrix_normal(), bem3d_element_local_vectors(), bem3d_element_nearest_vertex(), bem3d_element_normal(), bem3d_element_position(), bem3d_quadrature_parameter(), and bem3d_quadrature_rule_series().
bem3d_element_vertex_xi
#define bem3d_element_vertex_xi(e, i)
Parameters
e a BEM3DElement
i local index of a collocation point on e
Returns
the local coordinate $\xi$ of the i th vertex of e.
Referenced by bem3d_element_build_t0(), bem3d_element_build_t3(), bem3d_element_nearest_point(), and bem3d_mesh_read().
Typedef Documentation
BEM3DElement
 BEM3DElement
Data type for BEM3D elements, containing the data for geometry and collocation points.
The BEM3DElement type should usually be accessed only through the provided functions and macros. In order to implement new elements, you should look up the BEM3DElementBuildFunc type.
BEM3DElementClass
 BEM3DElementClass
The basic class for a BEM3DElement
Function Documentation
bem3d_element_add_face()
gint bem3d_element_add_face (BEM3DElement * e, gpointer f, gint i)
Add a new face to a BEM3DElement.
Parameters
e pointer to element;
f pointer to face to add;
i local face index for new face.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_face_number.
Referenced by bem3d_element_build_t0(), bem3d_element_build_t3(), and bem3d_mesh_read().
bem3d_element_add_node()
gint bem3d_element_add_node (BEM3DElement * e, gpointer v, gint i)
Add a collocation point to a BEM3DElement
Parameters
e pointer to BEM3DElement;
v pointer to vertex to add;
i local index of collocation point.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_node_number.
Referenced by bem3d_element_build_t0(), and bem3d_mesh_read().
bem3d_element_add_vertex()
gint bem3d_element_add_vertex (BEM3DElement * e, gpointer v, gint i)
Add a GtsVertex to a BEM3DElement.
Parameters
e pointer to BEM3DElement;
v pointer to GtsVertex to add;
i local index of GtsVertex.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_vertex_number.
Referenced by bem3d_element_build_q2(), bem3d_element_build_t0(), bem3d_element_build_t3(), and bem3d_mesh_read().
bem3d_element_area()
gdouble bem3d_element_area (BEM3DElement * e, gint ngp)
Surface area of a BEM3DElement, computed using a Gaussian quadrature rule.
Parameters
e BEM3DElement;
ngp number of quadrature points to use.
Returns
computed area of e.
References bem3d_element_jacobian(), bem3d_element_node_number, bem3d_element_shape_func, bem3d_quadrature_rule_new(), and bem3d_quadrature_rule_wx().
bem3d_element_assemble_equations()
gint bem3d_element_assemble_equations (BEM3DElement * e, GtsPoint * x, BEM3DConfiguration * config, BEM3DParameters * gdata, GArray * G, GArray * dGdn)
Assemble equations for BEM3DElement and GtsPoint.
The integration of the Green's function and its normal derivative weighted by the element shape functions is performed for a specified field point.
Parameters
e BEM3DElement;
x GtsPoint;
config BEM3DConfiguration configuration for this problem;
gdata BEM3DParameters to pass to Green's function;
G GArray of integral of $G L_{i}$ over element;
dGdn GArray of integral of $d G/d n L_{i}$ over element.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_node_func, bem3d_element_node_number, bem3d_element_normal(), bem3d_element_position(), bem3d_element_shape_func, bem3d_greens_function_func, and bem3d_quadrature_rule_new().
bem3d_element_assemble_equations_direct()
gint bem3d_element_assemble_equations_direct (BEM3DElement * e, GtsPoint * x, gint ix, BEM3DConfiguration * config, BEM3DParameters * gdata, gdouble * a, gdouble * b)
Assemble equations for an element inserting directly into matrix rows. Coefficients are accumulated directly in rows assuming zero-offset indexing, with stride 1 for real problems and 2 for complex, as determined from the Green's function.
Parameters
e a BEM3DElement
x field (collocation) point
ix index of x
config BEM3DConfiguration for the problem
gdata parameters for Green's function
a matrix row which multiplies potential ($\phi$)
b matrix row which multiplies normal derivative of potential ($\partial\phi/\partial n$)
Returns
::BEM3D_SUCCESS on success
References bem3d_element_global_index, bem3d_element_node_func, bem3d_element_node_number, bem3d_element_normal(), bem3d_element_position(), bem3d_element_shape_func, bem3d_greens_function_func, bem3d_greens_function_is_real, and bem3d_quadrature_rule_new().
bem3d_element_boundary_nearest_point()
gint bem3d_element_boundary_nearest_point (BEM3DElement * e, GtsPoint * x, gdouble * xi, gdouble * eta)
Find the area coordinates of the point on any edge of an element which is closest to a point x.
Parameters
e BEM3DElement
x ::GtsPoint
xi first area coordinate of point on edge c0--c1 which is closest to x
eta second area coordinate of point on edge i--j which is closest to x
Returns
::BEM3D_SUCCESS on success
References bem3d_element_shape_func.
bem3d_element_bounding_box()
GtsBBox* bem3d_element_bounding_box (GtsBBoxClass * klass, BEM3DElement * e)
Generate a ::GtsBBox containing the vertices of a BEM3DElement.
Parameters
klass a GtsBBoxClass;
e a BEM3DElement;
Returns
a ::GtsBBox containing the vertices of e or NULL on error.
References bem3d_element_vertex, and bem3d_element_vertex_number.
bem3d_element_class()
 BEM3DElementClass* bem3d_element_class (void)
The basic class for a BEM3DElement.
Returns
the BEM3DElementClass
Referenced by bem3d_element_build_q2(), bem3d_element_build_t0(), bem3d_element_build_t2(), bem3d_element_build_t3(), and bem3d_mesh_read().
bem3d_element_common_nodes()
GSList* bem3d_element_common_nodes (BEM3DElement * e1, BEM3DElement * e2)
Find collocation points shared between two BEM3DElement's.
Parameters
e1 BEM3DElement;
e2 BEM3DElement.
Returns
GSList of common collocation points.
References bem3d_element_find_node(), bem3d_element_node, and bem3d_element_node_number.
bem3d_element_edge_nearest_point()
gint bem3d_element_edge_nearest_point (BEM3DElement * e, gint i, gint j, GtsPoint * x, gdouble * xi, gdouble * eta)
Find the area coordinates of the point on the edge of an element which is closest to a point x.
Parameters
e BEM3DElement
i index of first corner of edge
j index of second corner of edge
x ::GtsPoint
xi first area coordinate of point on edge c0--c1 which is closest to x
eta second area coordinate of point on edge i--j which is closest to x
Returns
::BEM3D_SUCCESS on success.
bem3d_element_find_index()
gint bem3d_element_find_index (BEM3DElement * e, gint i)
Locate a node of given global index on a BEM3DElement
Parameters
e a BEM3DElement;
i global index of a node.
Returns
local index of a node of e with global index i, if found, -1 otherwise.
References bem3d_element_global_index, and bem3d_element_node_number.
Referenced by bem3d_edge_is_oriented(), and bem3d_mesh_node_elements().
bem3d_element_find_node()
gint bem3d_element_find_node (BEM3DElement * e, GtsVertex * v)
Find the local index of a collocation point on a BEM3DElement.
Parameters
e BEM3DElement to search;
v collocation point (GtsVertex) to find.
Returns
local index of collocation point if on element, -1 otherwise.
Referenced by bem3d_element_common_nodes(), bem3d_element_from_node(), bem3d_mesh_index_from_node(), and bem3d_quadrature_rule_series().
bem3d_element_find_vertex()
gint bem3d_element_find_vertex (BEM3DElement * e, GtsVertex * v)
Find the local index of a GtsVertex on a BEM3DElement.
Parameters
e BEM3DElement to search;
v GtsVertex to find.
Returns
local index of vertex if on element, -1 otherwise.
Referenced by bem3d_element_nearest_point(), bem3d_elements_from_vertices(), and bem3d_mesh_vertex_index_number().
bem3d_element_from_node()
 BEM3DElement* bem3d_element_from_node (BEM3DMesh * m, GtsVertex * v, gint i)
Find an element containing a given collocation point, identified by its GtsVertex and its global index.
Parameters
m BEM3DMesh
v GtsVertex of collocation point
i global index of collocation point
Returns
BEM3DElement containing v with index i.
References bem3d_element_find_node(), bem3d_element_global_index, BEM3D_IS_MESH, and bem3d_mesh_vertex_elements().
bem3d_element_gradient_weights()
gint bem3d_element_gradient_weights (BEM3DElement * e, gdouble xi, gdouble eta, gdouble * w)
Calculate the weights for computing the gradient of a function on a BEM3DElement. The gradient $\partial\phi/\partial x=\sum_{i=0}^{N}\phi_{i}w_{3i}$, $\partial\phi/\partial y=\sum_{i=0}^{N}\phi_{i}w_{3i+1}$, $\partial\phi/\partial z=\sum_{i=0}^{N}\phi_{i}w_{3i+2}$, where there are $N$ collocation points on the element e. The weights are computed by differentiation of the element shape functions.
Parameters
e BEM3DElement
xi local coordinate
eta local coordinate
w array of weights, which should be presized to at least $3N$ entries.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_local_vectors(), bem3d_element_node_number, bem3d_element_shape_func, bem3d_matrix_inverse(), and bem3d_matrix_vector_mul().
bem3d_element_has_node()
gboolean bem3d_element_has_node (BEM3DElement * e, GtsVertex * v)
Check if a GtsVertex is a node (collocation point) of a BEM3DElement.
Parameters
e BEM3DElement;
v GtsVertex.
Returns
TRUE if v is a node of e, FALSE otherwise.
References bem3d_element_node_number.
bem3d_element_has_vertex()
gboolean bem3d_element_has_vertex (BEM3DElement * e, GtsVertex * v)
Check if a GtsVertex is a vertex of the geometry of a BEM3DElement.
Parameters
e BEM3DElement;
v GtsVertex.
Returns
TRUE if vertex is on element, FALSE otherwise.
References bem3d_element_vertex_number.
bem3d_element_index_nodes()
gint bem3d_element_index_nodes (BEM3DElement * e, BEM3DMesh * m, gint * n)
Index the collocation points of a BEM3DElement. If a point is present in the BEM3DMesh m, the collocation point there is used. If not, new indices are generated, starting from n, which is incremented as required.
Parameters
e BEM3DElement to index
m BEM3DMesh for index checking
n first new index to assign, incremented as new indices are generated.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_node, bem3d_element_node_number, bem3d_element_set_index(), BEM3D_IS_MESH, and bem3d_mesh_index_from_node().
bem3d_element_jacobian()
gdouble bem3d_element_jacobian (BEM3DElement * e, gdouble * dLds, gdouble * dLdt)
Compute Jacobian on a BEM3DElement given derivatives of shape functions.
Parameters
e BEM3DElement;
dLds shape function derivatives $\partial L_{i}/\partial \xi$;
dLdt shape function derivatives $\partial L_{i}/\partial \eta$.
Returns
Jacobian.
References bem3d_element_vertex_number.
Referenced by bem3d_element_area().
bem3d_element_jacobian_matrix_normal()
gint bem3d_element_jacobian_matrix_normal (BEM3DElement * e, gdouble * dLds, gdouble * dLdt, GtsVector normal, gdouble * J, gdouble * Ji)
Compute Jacobian matrix, inverse and normal to an element.
Parameters
e a BEM3DElement;
dLds shape function derivatives $\partial L_{i}/\partial \xi$;
dLdt shape function derivatives $\partial L_{i}/\partial \eta$;
normal GtsVector for normal;
J nine-element matrix for Jacobian;
Ji nine-element matrix for inverse of Jacobian or NULL.
Returns
0 on success. If normal, J, and/or Ji are NULL, they are not computed, though if Ji is not NULL, J must also be defined.
References bem3d_element_vertex_number.
bem3d_element_local_vectors()
gint bem3d_element_local_vectors (BEM3DElement * e, gdouble dLds[], gdouble dLdt[], GtsVector u1, gdouble * h1, GtsVector u2, gdouble * h2)
Generate two unit vectors, not necessarily orthogonal, which lie in the surface at a point of a BEM3DElement.
Parameters
e BEM3DElement
dLds derivative of geometric shape function at required point of e
dLdt derivative of geometric shape function at required point of e
u1 first local vector $d x/d\xi/h_{1}$
h1 scale factor $h_{1}=|d x/d\xi|$
u2 first local vector $d x/d\xi/h_{2}$
h2 scale factor $h_{2}=|d x/d\xi|$
Returns
::BEM3D_SUCCESS on success
References bem3d_element_vertex, and bem3d_element_vertex_number.
Referenced by bem3d_element_gradient_weights().
bem3d_element_nearest_point()
gint bem3d_element_nearest_point (BEM3DElement * e, GtsPoint * x, gdouble * xi, gdouble * eta, gboolean constrain)
Given a BEM3DElement, find the area coordinates of the nearest point to a specified GtsPoint, using a rootfinding method. The point found need not lie on the BEM3DElement proper. For a plane element, this is equivalent to projection onto the plane.
Parameters
e BEM3DElement;
x GtsPoint;
xi first area coordinate of nearest point on BEM3DElement;
eta second area coordinate of nearest point on BEM3DElement;
constrain if TRUE, limit the search to points which lie on the element or its boundary; if FALSE, the returned point may lie outside the element.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_find_vertex(), bem3d_element_vertex_eta, and bem3d_element_vertex_xi.
bem3d_element_nearest_vertex()
gint bem3d_element_nearest_vertex (BEM3DElement * e, GtsPoint * p, gint * i, gdouble * R)
Find element vertex which is closest to a GtsPoint.
Parameters
e BEM3DElement;
p GtsPoint;
i local index of closest vertex;
R distance to closest vertex.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_vertex_number.
bem3d_element_neighbours()
GSList* bem3d_element_neighbours (BEM3DElement * el, BEM3DMesh * m)
Find the elements of a BEM3DMesh which share an edge with a specified element.
Parameters
el BEM3DElement whose neighbours are sought;
m BEM3DMesh.
Returns
a GSList of unique elements which border the specified element.
References bem3d_element_face, bem3d_element_face_number, BEM3D_IS_MESH, and bem3d_mesh_face_element().
bem3d_element_new()
 BEM3DElement* bem3d_element_new (BEM3DElementClass * klass, gint nf, gint nv, gint nc, gint ns, BEM3DShapeFunc shf, BEM3DShapeFunc cpf)
Allocate a new BEM3DElement
Parameters
klass BEM3DElementClass (use bem3d_element_class());
nf number of GtsFace on the element;
nv number of vertices for geometric interpolation;
nc number of collocation points (not necessarily the same as nv); set nc to zero make the collocation points coincide with the geometric vertices;
ns number of sides/corners (e.g. three for triangular elements);
shf pointer to shape function for geometry;
cpf pointer to shape function for collocation.
Returns
pointer to new element.
References bem3d_element_moment_order.
Referenced by bem3d_element_build_q2(), bem3d_element_build_t0(), bem3d_element_build_t2(), bem3d_element_build_t3(), and bem3d_mesh_read().
bem3d_element_normal()
gint bem3d_element_normal (BEM3DElement * e, gdouble * dLds, gdouble * dLdt, GtsVector normal, gdouble * J)
Compute normal to, and Jacobian on, a BEM3DElement given shape function derivatives.
Parameters
e BEM3DElement;
dLds shape function derivatives $\partial L_{i}/\partial \xi$;
dLdt shape function derivatives $\partial L_{i}/\partial \eta$;
normal GtsVector for normal;
J Jacobian.
Returns
::BEM3D_SUCCESS on success;
References bem3d_element_vertex_number.
Referenced by bem3d_element_assemble_equations(), bem3d_element_assemble_equations_direct(), bem3d_element_radiation_point(), and bem3d_node_normal().
bem3d_element_point_inside()
gboolean bem3d_element_point_inside (BEM3DElement * e, gdouble xi, gdouble eta)
Given the local coordinates of a point on an element, check if it lies inside the element.
Parameters
e BEM3DElement
xi first local coordinate of point to check
eta second local coordinate of point to check
Returns
TRUE if (xi, eta) lies inside the element, FALSE otherwise.
bem3d_element_position()
gint bem3d_element_position (BEM3DElement * e, gdouble * L, GtsPoint * q)
Interpolate position on a BEM3DElement given a set of shape functions.
Parameters
e BEM3DElement;
L array of shape functions for element;
q preallocated GtsPoint for interpolated position.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_vertex_number.
Referenced by bem3d_element_assemble_equations(), bem3d_element_assemble_equations_direct(), and bem3d_element_radiation_point().
bem3d_element_set_corner()
gint bem3d_element_set_corner (BEM3DElement * e, gint i, gint j)
Set a corner of a BEM3DElement.
Parameters
e BEM3DElement to set;
i local index of corner vertex;
j index of corner to set.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_corner_number.
Referenced by bem3d_element_build_q2(), bem3d_element_build_t0(), bem3d_element_build_t3(), and bem3d_mesh_read().
bem3d_element_set_index()
gint bem3d_element_set_index (BEM3DElement * e, gint i, gint j)
Set the global index of a collocation point.
Parameters
e pointer to BEM3DElement;
i local index;
j global index.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_node_number.
Referenced by bem3d_element_index_nodes(), and bem3d_mesh_read().
bem3d_element_vertex_is_corner()
gint bem3d_element_vertex_is_corner (BEM3DElement * e, GtsVertex * v)
Check if a vertex is a corner of an element.
Parameters
e a BEM3DElement;
v a GtsVertex of e.
Returns
the index of a corner of e if v is a corner, -1 otherwise.
References bem3d_element_corner, and bem3d_element_corner_number.
bem3d_element_write()
gint bem3d_element_write (BEM3DElement * e, GHashTable * v, GHashTable * t, FILE * f)
Write a BEM3DElement to file. Usually called from bem3d_mesh_write.
Format: nf nv nc ns shf cpf [faces] [vertices] [collocation points] [vertex area coordinate] [collocation point area coordinates] [collocation point global indices] [corner indices]
Parameters
e element to write;
v hash table of vertices;
t hash table of faces;
f file pointer.
Returns
::BEM3D_SUCCESS on success.
References bem3d_shapefunc_lookup_name().
bem3d_elements_common_edges()
GSList* bem3d_elements_common_edges (BEM3DElement * e1, BEM3DElement * e2)
Find the GtsEdge's common to two BEM3DElement's.
Parameters
e1 BEM3DElement
e2 BEM3DElement
Returns
a GSList of GtsEdges common to e1 and e2, or NULL if the elements do not touch.
References bem3d_element_face, and bem3d_element_face_number.
bem3d_elements_from_vertices()
GSList* bem3d_elements_from_vertices (BEM3DMesh * m, GtsVertex * v1, GtsVertex * v2)
Find the BEM3DElement s shared by two GtsVertex s.
Parameters
m a BEM3DMesh;
v1 a vertex of m;
v2 another vertex of m;
Returns
a GSList of BEM3DElement s of m which contain both v1 and v2.
References bem3d_element_find_vertex(), BEM3D_IS_MESH, and bem3d_mesh_vertex_elements().
Referenced by bem3d_edge_is_oriented().