Differential (and other) operators
Data Structures
struct BEM3DOperator
Macros
#define bem3d_operator_size(op)
#define bem3d_operator_length(op)
#define bem3d_operator_index(op, i)
#define bem3d_operator_weight(op, i)
Enumerations
enum BEM3DAverage {
*
BEM3D_AVERAGE_MWE,
BEM3D_AVERAGE_MWA,
BEM3D_AVERAGE_MWSELR,
BEM3D_AVERAGE_MWAAT,
*
BEM3D_AVERAGE_MWELR,
BEM3D_AVERAGE_MWRELR
 }
Functions
BEM3DOperator * bem3d_operator_new (void)
gint bem3d_node_normal (BEM3DMesh *m, gint i, GtsVector n, BEM3DAverage mode)
gint bem3d_operator_gradient (BEM3DMesh *m, gint i, BEM3DOperator *op, BEM3DAverage mode)
Detailed Description
BEM3D contains a number of functions for computing differential operators applied to surface quantities. These are returned in a BEM3DOperator which can be applied to surface data using the appropriate functions. For example, to compute an estimate of the gradient of a function defined at nodes of a mesh:
BEM3DOperator *op ;
GtsVector df ;
gdouble *opi ;
op = bem3d_operator_new() ;
bem3d_operator_gradient(m, i, op, BEM3D_AVERAGE_MWSELR) ;
df[0] = df[1] = df[2] = 0.0 ;
for (j = 0 ; j < bem3d_operator_length(op) ; j ++) {
   opi = bem3d_operator_weight(op,j) ;
   df[0] += f[bem3d_operator_index(op,j)]*opi[0] ;
   df[1] += f[bem3d_operator_index(op,j)]*opi[1] ;
   df[2] += f[bem3d_operator_index(op,j)]*opi[2] ;
}
For now, these operators are limited to first order triangular elements.
Macro Definition Documentation
#define bem3d_operator_index(op, i)
Global index of the i th node forming the operator op
#define bem3d_operator_length(op)
The number of nodes used in computing a BEM3DOperator op
#define bem3d_operator_size(op)
The number of elements in a BEM3DOperator op, e.g. three elements for a gradient operator, one for a Laplacian.
#define bem3d_operator_weight(op, i)
Weight for the x-component of i th node forming the operator op
Enumeration Type Documentation
enum BEM3DAverage
Modes of calculating differential operators and vertex normals from quantities on connected elements.
Enumerator
BEM3D_AVERAGE_MWE
 Mean weighted equally
BEM3D_AVERAGE_MWA
 Mean weighted by angle
BEM3D_AVERAGE_MWSELR
 Mean weighted by sine and edge length reciprocal
BEM3D_AVERAGE_MWAAT
 Mean weighted by areas of adjacent triangles
BEM3D_AVERAGE_MWELR
 Mean weighted by edge length reciprocals
BEM3D_AVERAGE_MWRELR
 Mean weighted by square root of edge length reciprocals
Function Documentation
gint bem3d_node_normal (BEM3DMesh * m, gint i, GtsVector n, BEM3DAverage mode)
Compute the surface normal at a node as the weighted average, where appropriate, of the normals on each of the elements of a mesh using the node, using the methods in Jin, S., Lewis, R. and West, D., `A comparison of algorithms for vertex normal computation', The Visual Computer, 21(1-2):71--82, http://dx.doi.org/10.1007/s00371-004-0271-1
Parameters
m a BEM3DMesh;
i index of a node of m;
n the normal at node i;
mode a BEM3DAverage defining the averaging method to be used.
Returns
References BEM3D_AVERAGE_MWA, BEM3D_AVERAGE_MWAAT, BEM3D_AVERAGE_MWE, BEM3D_AVERAGE_MWELR, BEM3D_AVERAGE_MWRELR, BEM3D_AVERAGE_MWSELR, bem3d_element_normal(), bem3d_element_shape_func, BEM3D_IS_MESH, bem3d_mesh_node_elements(), and bem3d_mesh_node_from_index().
gint bem3d_operator_gradient (BEM3DMesh * m, gint i, BEM3DOperator * op, BEM3DAverage mode)
Compute the operator for computation of the surface gradient of a quantity at a node of a BEM3DMesh. Currently, the function is only implemented for linear triangles, using the gradient discretization of Xu, G., `Convergent discrete Laplace-Beltrami operators over triangular surfaces', Proceedings of Geometric Modeling and Processing 2004 (GMP 04), http://dx.doi.org/10.1109/GMAP.2004.1290041 If any other element type is detected, the function returns silently.
Parameters
m a BEM3DMesh;
i index of a node of m;
op on exit, contains the operator for $\nabla_{T}f$;
mode a BEM3DAverage specifying the mode for averaging over elements (not all of these are implemented).
Returns
BEM3D_SUCCESS on success, an error code otherwise.
References BEM3D_AVERAGE_MWA, BEM3D_AVERAGE_MWAAT, BEM3D_AVERAGE_MWE, BEM3D_AVERAGE_MWELR, BEM3D_AVERAGE_MWRELR, BEM3D_AVERAGE_MWSELR, BEM3D_IS_MESH, bem3d_mesh_node_elements(), bem3d_mesh_node_from_index(), bem3d_shfunc_t0(), and bem3d_shfunc_t1().
BEM3DOperator* bem3d_operator_new (void)
Allocate a new BEM3DOperator.
Returns
a newly allocated BEM3DOperator.