Matrix operations
Typedefs
typedef gdouble BEM3DMatrix[9]
Functions
gint bem3d_matrix_vector_mul (BEM3DMatrix m, GtsVector v, GtsVector w)
gdouble bem3d_matrix_det (BEM3DMatrix m)
gint bem3d_matrix_inverse (BEM3DMatrix m, BEM3DMatrix im)
Detailed Description
Some basic matrix definitions and operations.
Typedef Documentation
BEM3DMatrix
typedef gdouble BEM3DMatrix[9]
A basic definition of a 3x3 matrix.
Function Documentation
bem3d_matrix_det()
gdouble bem3d_matrix_det (BEM3DMatrix m)
Evaluate the determinant of a BEM3DMatrix
Parameters
m BEM3DMatrix
Returns
determinant of m
Referenced by bem3d_matrix_inverse().
bem3d_matrix_inverse()
gint bem3d_matrix_inverse (BEM3DMatrix m, BEM3DMatrix im)
Find the inverse of a BEM3DMatrix.
Parameters
m BEM3DMatrix
im BEM3DMatrix to hold inverse of m
Returns
::BEM3D_SUCCESS on success or ::BEM3D_FAILURE if m is singular.
References bem3d_matrix_det().
Referenced by bem3d_element_gradient_weights().
bem3d_matrix_vector_mul()
gint bem3d_matrix_vector_mul (BEM3DMatrix m, GtsVector v, GtsVector w)
Multiply a BEM3DMatrix by a GtsVector.
Parameters
m BEM3DMatrix
v GtsVector to multiply
w GtsVector for result of operation
Returns
0 on success.
Referenced by bem3d_element_gradient_weights().