Motion specification
Functions
BEM3DMotionClass * bem3d_motion_class (void)
 BEM3DMotion * bem3d_motion_new (BEM3DMotionClass *klass, BEM3DMesh *m, BEM3DMesh *m0)
gint bem3d_motion_variable_add (BEM3DMotion *m, gchar *var, gchar *def)
gchar * bem3d_motion_variable_lookup (BEM3DMotion *m, gchar *var)
gint bem3d_motion_write (BEM3DMotion *m, FILE *f)
gint bem3d_motion_expand_defs (BEM3DMotion *m)
gint bem3d_motion_write_expansions (BEM3DMotion *m, FILE *f)
gint bem3d_motion_create_evaluators (BEM3DMotion *m)
gint bem3d_motion_free_evaluators (BEM3DMotion *m)
gint bem3d_motion_mesh_position (BEM3DMotion *m, gdouble t)
gboolean bem3d_motion_token_is_reserved (gchar *token)
guint bem3d_motion_read (BEM3DMotion *m, GtsFile *f)
gint bem3d_motion_node_velocity (BEM3DMotion *m, gint i, gdouble t, GtsVector u)
gint bem3d_motion_node_acceleration (BEM3DMotion *m, gint i, gdouble t, GtsVector a)
Detailed Description
BEM3D contains a simple interpreter, using the libmatheval library (http://www.gnu.org/software/libmatheval/) of Aleksandar Samardzic, which can be used to analytically specify the motion of the nodes of a BEM3DMesh and analytically derive the surface velocity for use in the boundary condition. Motion definitions are defined using equations of the form `x = ...', where the right hand side may include other user-defined functions and constants. See bem3d_motion_variable_add to see how this works.
Function Documentation
bem3d_motion_class()
BEM3DMotionClass* bem3d_motion_class (void)
The basic class for a BEM3DMotion.
Returns
the class definition for a BEM3DMotion.
bem3d_motion_create_evaluators()
gint bem3d_motion_create_evaluators (BEM3DMotion * m)
Create the libmatheval (http://www.gnu.org/software/libmatheval/) evaluators for the expressions of a BEM3DMotion, prior to evaluating node positions for a BEM3DMesh. If BEM3D has been compiled without libmatheval support, this function will fail.
Parameters
m a BEM3DMotion.
Returns
BEM3D_SUCCESS on success.
bem3d_motion_expand_defs()
gint bem3d_motion_expand_defs (BEM3DMotion * m)
Expand the equations for surface variables (displacement and velocity) in a BEM3DMotion to give expressions in terms of the reserved tokens only so that the variables can be evaluated using bem3d_motion_mesh_position.
Parameters
m the BEM3DMotion whose expressions are to be expanded.
Returns
::BEM3D_SUCCESS on success.
bem3d_motion_free_evaluators()
gint bem3d_motion_free_evaluators (BEM3DMotion * m)
Free the function evaluators of a BEM3DMotion. Note that this does not affect the stored expressions, only the libmatheval evaluators. This function will fail if BEM3D has been compiled without libmatheval support.
Parameters
m a BEM3DMotion.
Returns
BEM3D_SUCCESS on success.
bem3d_motion_mesh_position()
gint bem3d_motion_mesh_position (BEM3DMotion * m, gdouble t)
Position the nodes of a BEM3DMesh linked to a BEM3DMotion.
Parameters
m the BEM3DMotion containing a mesh;
t time variable.
Returns
BEM3D_SUCCESS on success.
References bem3d_mesh_foreach_node().
bem3d_motion_new()
 BEM3DMotion* bem3d_motion_new (BEM3DMotionClass * klass, BEM3DMesh * m, BEM3DMesh * m0)
Generate a new BEM3DMotion.
Parameters
klass a ::BEM3DMotionClass;
m a BEM3DMesh to which the motion equations will be applied;
m0 a BEM3DMesh which will be used as the reference geometry in computing the motion. The BEM3DMotion is initialized with the default equations `x = x0', `y = y0', `z = z0', `u = 0', `v = 0', `w = 0', `nx = 0', `ny = 0', `nz = 0'.
Returns
the new BEM3DMotion.
References bem3d_mesh_node_number().
bem3d_motion_node_acceleration()
gint bem3d_motion_node_acceleration (BEM3DMotion * m, gint i, gdouble t, GtsVector a)
Evaluate the acceleration of a node on a mesh from the position specification in a BEM3DMotion.
Parameters
m a BEM3DMotion which has been initialized and had its evaluators set using bem3d_motion_create_evaluators;
i index of the node whose acceleration is to be computed;
t time;
a on exit contains acceleration of node i.
Returns
BEM3D_SUCCESS on success.
References bem3d_mesh_node_from_index().
bem3d_motion_node_velocity()
gint bem3d_motion_node_velocity (BEM3DMotion * m, gint i, gdouble t, GtsVector u)
Evaluate the velocity of a node on a mesh from the position specification in a BEM3DMotion.
Parameters
m a BEM3DMotion which has been initialized and had its evaluators set using bem3d_motion_create_evaluators;
i index of the node whose velocity is to be computed;
t time;
u on exit contains velocity of node i.
Returns
BEM3D_SUCCESS on success.
References bem3d_mesh_node_from_index().
bem3d_motion_read()
guint bem3d_motion_read (BEM3DMotion * m, GtsFile * f)
Read the definition of a BEM3DMotion from file. The file format is that used by bem3d_motion_write.
Parameters
m a BEM3DMotion to which the definitions should be added;
f a GtsFile for the input stream.
Returns
0 on success or the line number in the input file where an error was encountered.
References bem3d_motion_variable_add().
bem3d_motion_token_is_reserved()
gboolean bem3d_motion_token_is_reserved (gchar * token)
Check if a token is a reserved word for a BEM3DMotion function.
Parameters
token a string containing a potential token.
Returns
TRUE if token is a reserved word for BEM3DMotion functions.
Referenced by bem3d_motion_variable_add().
bem3d_motion_variable_add()
gint bem3d_motion_variable_add (BEM3DMotion * m, gchar * var, gchar * def)
Add a variable definition to a BEM3DMotion, in the form var = def. The variable name var may not be one of the reserved tokens but may otherwise be any valid libmatheval token. The variables which must be defined (and are given default definitions in BEM3DMotion) are $x$, $y$, $z$ which will be evaluated to give the node position and $u$, $v$ and $w$ which will give the surface velocity, other than that due to surface motion (e.g. in scattering problems). Reserved tokens are $x0$, $y0$, $z0$, the position of a node on the reference BEM3DMesh, $nx$, $ny$, $nz$, $nx0$, $ny0$, $nz0$, the components of the local surface normal on the mesh and the reference mesh respectively, $t$, time, $i$, the node index and $j$, the complex variable.
Parameters
m a BEM3DMotion;
var the name of the variable to add or redefine;
def the definition of var.
Returns
::BEM3D_SUCCESS on success.
References bem3d_motion_token_is_reserved().
Referenced by bem3d_motion_read().
bem3d_motion_variable_lookup()
gchar* bem3d_motion_variable_lookup (BEM3DMotion * m, gchar * var)
Find the definition of a variable in a BEM3DMotion.
Parameters
m a BEM3DMotion.
var the name of the variable to look up.
Returns
the definition of var or NULL if var is not defined in m.
bem3d_motion_write()
gint bem3d_motion_write (BEM3DMotion * m, FILE * f)
Write the definitions in a BEM3DMotion to file. The file format is a header line `BEM3DMotion', followed by the variable definitions, one per line, in the format: `x = ...'.
Parameters
m the BEM3DMotion to write to file;
f file to which m is to be written.
Returns
BEM3D_SUCCESS on success.
bem3d_motion_write_expansions()
gint bem3d_motion_write_expansions (BEM3DMotion * m, FILE * f)
Write the expanded expressions for displacement and velocity in a BEM3DMotion to file. There is no need to do this to store a BEM3DMotion: bem3d_motion_write should be used instead.
Parameters
m a BEM3DMotion;
f a FILE to which the expansions in m should be written.
Returns
BEM3D_SUCCESS on success.