BEM3D meshes
Data Structures
struct BEM3DMesh
struct BEM3DMeshClass
Macros
#define BEM3D_MESH(obj)
#define BEM3D_MESH_CLASS(klass)
#define BEM3D_IS_MESH(obj)
#define bem3d_mesh_element_number(m)
#define bem3d_mesh_node_index_min(m)
#define bem3d_mesh_node_index_max(m)
Functions
 BEM3DMeshClass * bem3d_mesh_class (void)
 BEM3DMesh * bem3d_mesh_new (BEM3DMeshClass *klass, GtsFaceClass *face_class, GtsEdgeClass *edge_class, GtsVertexClass *vertex_class)
gint bem3d_mesh_add_element (BEM3DMesh *m, BEM3DElement *e, gboolean force)
GSList * bem3d_mesh_vertex_elements (BEM3DMesh *m, GtsVertex *v)
gint bem3d_mesh_index_nodes (BEM3DMesh *m, gdouble angle, gint ni)
gint bem3d_mesh_discretize (GtsSurface *s, gint nne, BEM3DElementBuildFunc bfunc, BEM3DMesh *m)
gint bem3d_mesh_node_number (BEM3DMesh *m)
gint bem3d_mesh_assemble_equations (BEM3DMesh *m, BEM3DMesh *n, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DEquationFunc efunc, gpointer edata)
gint bem3d_mesh_foreach_element (BEM3DMesh *m, BEM3DElementFunc f, gpointer data)
gint bem3d_mesh_foreach_node (BEM3DMesh *m, BEM3DNodeFunc f, gpointer data)
gint bem3d_mesh_set_bc (BEM3DMesh *m, BEM3DBCFunc bcf, gpointer bdata)
gint bem3d_mesh_quad_dgdn (BEM3DMesh *m, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DEquationFunc efunc, gpointer edata)
gint bem3d_mesh_disjoint_quad_dgdn (BEM3DMesh *m1, BEM3DMesh *m2, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DEquationFunc efunc, gpointer edata)
 BEM3DElement * bem3d_mesh_face_element (BEM3DMesh *m, GtsFace *f)
GtsVertex * bem3d_mesh_node_from_index (BEM3DMesh *m, gint i)
gint bem3d_mesh_index_from_node (BEM3DMesh *m, GtsVertex *v)
GSList * bem3d_mesh_node_elements (BEM3DMesh *m, gint i)
gint bem3d_mesh_element_node_number_max (BEM3DMesh *m)
gint bem3d_mesh_index_range (BEM3DMesh *m, gint *imin, gint *imax)
 BEM3DElement * bem3d_mesh_element_sample (BEM3DMesh *m)
gdouble bem3d_mesh_surface_area (BEM3DMesh *m, gint ngp)
gint bem3d_mesh_write (BEM3DMesh *m, FILE *f)
guint bem3d_mesh_read (BEM3DMesh *m, GtsFile *f)
gint bem3d_mesh_write_nodes (BEM3DMesh *m, FILE *f)
guint bem3d_gmsh_read (BEM3DMesh *m, FILE *f)
Detailed Description
Macro Definition Documentation
BEM3D_IS_MESH
#define BEM3D_IS_MESH(obj)
TRUE if obj is from the BEM3DMeshClass class
Referenced by bem3d_edge_is_oriented(), bem3d_element_from_node(), bem3d_element_index_nodes(), bem3d_element_neighbours(), bem3d_elements_from_vertices(), bem3d_gmsh_read(), bem3d_mesh_add_element(), bem3d_mesh_assemble_equations(), bem3d_mesh_data_new(), bem3d_mesh_discretize(), bem3d_mesh_disjoint_quad_dgdn(), bem3d_mesh_extract_edges(), bem3d_mesh_face_element(), bem3d_mesh_index_from_node(), bem3d_mesh_index_nodes(), bem3d_mesh_node_elements(), bem3d_mesh_node_from_index(), bem3d_mesh_node_number(), bem3d_mesh_quad_dgdn(), bem3d_mesh_radiation_mesh(), bem3d_mesh_radiation_point(), bem3d_mesh_read(), bem3d_mesh_set_bc(), bem3d_mesh_sharp_vertices(), bem3d_mesh_vertex_elements(), bem3d_mesh_vertex_index_number(), bem3d_mesh_write(), bem3d_mesh_write_nodes(), bem3d_node_normal(), and bem3d_operator_gradient().
BEM3D_MESH
#define BEM3D_MESH(obj)
Casts obj to BEM3DMesh
Parameters
obj a GtsObject
Returns
result of casting obj to BEM3DMesh.
Referenced by bem3d_mesh_new().
BEM3D_MESH_CLASS
#define BEM3D_MESH_CLASS(klass)
Casts klass to BEM3DMeshClass
Parameters
klass class to cast
bem3d_mesh_element_number
#define bem3d_mesh_element_number(m)
Number of elements in a BEM3DMesh
Referenced by bem3d_mesh_skeleton_init(), and bem3d_mesh_skeleton_new().
bem3d_mesh_node_index_max
#define bem3d_mesh_node_index_max(m)
Maximum index of node to be considered in bem3d_mesh_foreach_node
Referenced by bem3d_mesh_assemble_equations(), bem3d_mesh_data_new(), bem3d_mesh_disjoint_quad_dgdn(), bem3d_mesh_quad_dgdn(), bem3d_mesh_radiation_mesh(), and bem3d_mesh_radiation_point().
bem3d_mesh_node_index_min
#define bem3d_mesh_node_index_min(m)
Minimum index of node to be considered in bem3d_mesh_foreach_node
Referenced by bem3d_mesh_assemble_equations(), bem3d_mesh_data_new(), bem3d_mesh_disjoint_quad_dgdn(), bem3d_mesh_quad_dgdn(), bem3d_mesh_radiation_mesh(), and bem3d_mesh_radiation_point().
Function Documentation
bem3d_gmsh_read()
guint bem3d_gmsh_read (BEM3DMesh * m, FILE * f)
Read a GMSH 1.0 or 2.0 mesh file to a BEM3DMesh.
Parameters
m a BEM3DMesh;
f input file pointer.
Returns
BEM3D_SUCCESS on success.
References BEM3D_IS_MESH.
bem3d_mesh_add_element()
gint bem3d_mesh_add_element (BEM3DMesh * m, BEM3DElement * e, gboolean force)
Add an element to a BEM3DMesh, checking to see if it is already present.
Parameters
m BEM3DMesh to add element to
e element to add
force if TRUE force addition of the element vertices, even if e is present in m
Returns
::BEM3D_SUCCESS on success
References bem3d_element_global_index, bem3d_element_node_number, and BEM3D_IS_MESH.
Referenced by bem3d_mesh_read().
bem3d_mesh_assemble_equations()
gint bem3d_mesh_assemble_equations (BEM3DMesh * m, BEM3DMesh * n, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DEquationFunc efunc, gpointer edata)
Assemble the BEM3D equations for two meshes (which may be the same mesh)
Parameters
m BEM3DMesh whose elements are to be processed;
n BEM3DMesh whose nodes are to be processed;
config BEM3DConfiguration for the problem;
gdata BEM3DParameters for the Green's function;
efunc BEM3DEquationFunc for the problem
edata data to pass to efunc
Returns
::BEM3D_SUCCESS on success
References BEM3D_IS_MESH, bem3d_mesh_foreach_node(), bem3d_mesh_node_index_max, bem3d_mesh_node_index_min, and bem3d_mesh_node_number().
bem3d_mesh_class()
 BEM3DMeshClass* bem3d_mesh_class (void)
Definition of the BEM3DMeshClass.
Returns
BEM3DMeshClass
bem3d_mesh_discretize()
gint bem3d_mesh_discretize (GtsSurface * s, gint nne, BEM3DElementBuildFunc bfunc, BEM3DMesh * m)
Discretize a surface by splitting its triangles into higher order elements.
Parameters
s GtsSurface to be discretized;
nne number of nodes per edge of each triangular face;
bfunc BEM3DElementBuildFunc for the required element;
m BEM3DMesh to be generated.
Returns
::BEM3D_SUCCESS on success.
References BEM3D_IS_MESH.
bem3d_mesh_disjoint_quad_dgdn()
gint bem3d_mesh_disjoint_quad_dgdn (BEM3DMesh * m1, BEM3DMesh * m2, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DEquationFunc efunc, gpointer edata)
Integrate the normal derivative of the Green's function over a mesh at points on a different mesh. This is intended for use where a surface is broken into two or more disjoint patches which combine to form a single closed surface. The integratation is performed over m1 for each point on m2. The two meshes can be the same.
Parameters
m1 BEM3DMesh
m2 BEM3DMesh
config BEM3DConfiguration for the problem;
gdata BEM3DParameters to pass to Green's function;
lfunc BEM3DLookupFunc; use bem3d_lookup_func_unit (for real problems) or bem3d_lookup_func_unit_c (for complex)
ldata data to pass to the lookup function
efunc equation function for problem. This will be called with the row and column numbers equal.
edata user data to pass to efunc
Returns
::BEM3D_SUCCESS on success
References BEM3D_IS_MESH, bem3d_mesh_foreach_node(), bem3d_mesh_node_index_max, and bem3d_mesh_node_index_min.
bem3d_mesh_element_node_number_max()
gint bem3d_mesh_element_node_number_max (BEM3DMesh * m)
Find the largest number of nodes on an element of a BEM3DMesh
Parameters
m a BEM3DMesh
Returns
the maximum number of nodes on an element of m
References bem3d_mesh_foreach_element().
Referenced by bem3d_mesh_skeleton_new().
bem3d_mesh_element_sample()
 BEM3DElement* bem3d_mesh_element_sample (BEM3DMesh * m)
Select a sample element from a BEM3DMesh
Parameters
m a BEM3DMesh
Returns
a randomly chosen element from m
References bem3d_mesh_foreach_element().
bem3d_mesh_face_element()
 BEM3DElement* bem3d_mesh_face_element (BEM3DMesh * m, GtsFace * f)
Find the BEM3DElement of a BEM3DMesh containing a given GtsFace.
Parameters
m BEM3DMesh to search
f GtsFace to locate
Returns
BEM3DElement of m containing f or NULL if f is not in m.
References BEM3D_IS_MESH.
Referenced by bem3d_element_neighbours().
bem3d_mesh_foreach_element()
gint bem3d_mesh_foreach_element (BEM3DMesh * m, BEM3DElementFunc f, gpointer data)
Visit each element of a mesh and execute a function
Parameters
m mesh to process
f BEM3DElementFunc to call
data user data to pass to f
Returns
::BEM3D_SUCCESS on success
Referenced by bem3d_mesh_element_node_number_max(), bem3d_mesh_element_sample(), bem3d_mesh_index_nodes(), bem3d_mesh_radiation_point(), bem3d_mesh_set_bc(), bem3d_mesh_skeleton_init(), bem3d_mesh_surface_area(), and bem3d_reduction_func_int().
bem3d_mesh_foreach_node()
gint bem3d_mesh_foreach_node (BEM3DMesh * m, BEM3DNodeFunc f, gpointer data)
Visit each collocation point of a mesh and execute a function
Parameters
m mesh to process
f BEM3DNodeFunc to call
data user data to pass to f
Returns
::BEM3D_SUCCESS on success
Referenced by bem3d_fmm_matrix_new(), bem3d_mesh_assemble_equations(), bem3d_mesh_data_add_mesh(), bem3d_mesh_data_new(), bem3d_mesh_disjoint_quad_dgdn(), bem3d_mesh_index_range(), bem3d_mesh_node_number(), bem3d_mesh_quad_dgdn(), bem3d_mesh_radiation_mesh(), bem3d_mesh_write_nodes(), and bem3d_motion_mesh_position().
bem3d_mesh_index_from_node()
gint bem3d_mesh_index_from_node (BEM3DMesh * m, GtsVertex * v)
Find an index for a collocation point in a BEM3DMesh. Note that this index may not be unique, for example if the mesh has sharp edges.
Parameters
m BEM3DMesh
v GtsVertex for collocation point to find
Returns
index of v in m, or -1 if not found.
References bem3d_element_find_node(), bem3d_element_global_index, BEM3D_IS_MESH, and bem3d_mesh_vertex_elements().
Referenced by bem3d_element_index_nodes().
bem3d_mesh_index_nodes()
gint bem3d_mesh_index_nodes (BEM3DMesh * m, gdouble angle, gint ni)
Number the collocation points of a mesh, with sharp corners double indexed if the angle between two element normals at an edge is greater than angle.
Parameters
m BEM3DMesh to be numbered;
angle angle to be used in determining edge sharpness for double indexing;
ni initial index.
Returns
number of indices on success, which can be used as initial index for a subsequent mesh.
References BEM3D_IS_MESH, and bem3d_mesh_foreach_element().
bem3d_mesh_index_range()
gint bem3d_mesh_index_range (BEM3DMesh * m, gint * imin, gint * imax)
Find the maximum and minimum indices of a BEM3DMesh
Parameters
m a BEM3DMesh
imin minimum index
imax maximum index
Returns
BEM3D_SUCCESS on success
References bem3d_mesh_foreach_node().
Referenced by bem3d_mesh_skeleton_new().
bem3d_mesh_new()
 BEM3DMesh* bem3d_mesh_new (BEM3DMeshClass * klass, GtsFaceClass * face_class, GtsEdgeClass * edge_class, GtsVertexClass * vertex_class)
Create a new BEM3DMesh.
Parameters
klass the BEM3D mesh class for the mesh;
face_class the GTS face class;
edge_class the GTS edge class;
vertex_class the GTS vertex class.
Returns
a pointer to the newly created mesh
References BEM3D_MESH.
bem3d_mesh_node_elements()
GSList* bem3d_mesh_node_elements (BEM3DMesh * m, gint i)
Extract a linked list of the elements of a mesh containing a given node (collocation point).
Parameters
m BEM3DMesh;
i index of node on m.
Returns
linked list of elements containing node i, NULL otherwise.
References bem3d_element_find_index(), BEM3D_IS_MESH, and bem3d_mesh_node_from_index().
Referenced by bem3d_node_normal(), and bem3d_operator_gradient().
bem3d_mesh_node_from_index()
GtsVertex* bem3d_mesh_node_from_index (BEM3DMesh * m, gint i)
Find the GtsVertex on a BEM3DMesh containing a given collocation point.
Parameters
m BEM3DMesh to search;
i index of collocation point.
Returns
GtsVertex of m with collocation point index i or NULL if point i is not on m.
References BEM3D_IS_MESH.
Referenced by bem3d_edge_is_oriented(), bem3d_mesh_node_elements(), bem3d_motion_node_acceleration(), bem3d_motion_node_velocity(), bem3d_node_normal(), and bem3d_operator_gradient().
bem3d_mesh_node_number()
gint bem3d_mesh_node_number (BEM3DMesh * m)
Count the number of collocation points on a mesh
Parameters
m BEM3DMesh
Returns
number of nodes on m.
References BEM3D_IS_MESH, and bem3d_mesh_foreach_node().
Referenced by bem3d_mesh_assemble_equations(), bem3d_mesh_data_new(), bem3d_mesh_skeleton_init(), bem3d_mesh_skeleton_new(), and bem3d_motion_new().
bem3d_mesh_quad_dgdn()
gint bem3d_mesh_quad_dgdn (BEM3DMesh * m, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DEquationFunc efunc, gpointer edata)
Integrate the normal derivative of the Green's function over a mesh.
Parameters
m BEM3DMesh
config BEM3DConfiguration for the problem;
gdata BEM3DParameters to pass to Green's function;
lfunc BEM3DLookupFunc; use bem3d_lookup_func_unit (for real problems) or bem3d_lookup_func_unit_c (for complex)
ldata data to pass to the lookup function
efunc equation function for problem. This will be called with the row and column numbers equal.
edata user data to pass to efunc
Returns
::BEM3D_SUCCESS on success
References BEM3D_IS_MESH, bem3d_mesh_foreach_node(), bem3d_mesh_node_index_max, and bem3d_mesh_node_index_min.
bem3d_mesh_read()
guint bem3d_mesh_read (BEM3DMesh * m, GtsFile * f)
Read a BEM3DMesh from input file. This is a modified version of Stephane Popinet's original gts_surface_read
Parameters
m BEM3DMesh to read
f GtsFile to read from
Returns
0 on success, line number where error was encountered otherwise
References bem3d_element_add_face(), bem3d_element_add_node(), bem3d_element_add_vertex(), bem3d_element_class(), bem3d_element_new(), bem3d_element_node_eta, bem3d_element_node_xi, bem3d_element_set_corner(), bem3d_element_set_index(), bem3d_element_vertex_eta, bem3d_element_vertex_xi, BEM3D_IS_MESH, bem3d_mesh_add_element(), and bem3d_shapefunc_lookup_func().
bem3d_mesh_set_bc()
gint bem3d_mesh_set_bc (BEM3DMesh * m, BEM3DBCFunc bcf, gpointer bdata)
Set the boundary conditions on a mesh
Parameters
m mesh for boundary conditions
bcf BEM3DBCFunc
bdata user data to pass to bcf
Returns
::BEM3D_SUCCESS on success
References BEM3D_IS_MESH, and bem3d_mesh_foreach_element().
bem3d_mesh_surface_area()
gdouble bem3d_mesh_surface_area (BEM3DMesh * m, gint ngp)
Surface area of a BEM3DMesh by integrating over elements. This gives an accurate estimate of surface area for meshes with curvilinear elements.
Parameters
m a BEM3DMesh
ngp number of points in quadrature rule, for call to bem3d_element_area
Returns
surface area of m
References bem3d_mesh_foreach_element().
bem3d_mesh_vertex_elements()
GSList* bem3d_mesh_vertex_elements (BEM3DMesh * m, GtsVertex * v)
Extract a linked list of the elements of a mesh containing a given vertex.
Parameters
m BEM3DMesh containing vertex;
v vertex to check.
Returns
GSList of elements connected to v.
References BEM3D_IS_MESH.
Referenced by bem3d_element_from_node(), bem3d_elements_from_vertices(), bem3d_mesh_index_from_node(), and bem3d_mesh_vertex_index_number().
bem3d_mesh_write()
gint bem3d_mesh_write (BEM3DMesh * m, FILE * f)
Write a BEM3DMesh to a file using part of Stephane Popinet's GTS function for writing a GTS surface.
Parameters
m mesh to write;
f file pointer to write to.
Returns
BEM3D_SUCCESS on success.
The output file is a GtsSurface file followed by the element data as follows:
number of elements
element data as specified in bem3d_element_write, one element per line
References BEM3D_IS_MESH.
bem3d_mesh_write_nodes()
gint bem3d_mesh_write_nodes (BEM3DMesh * m, FILE * f)
Write the nodes and normals of a BEM3DMesh, one per line, to output in the format:
[node index] x y z nx ny nz
Parameters
m BEM3DMesh to write;
f file pointer.
Returns
0 on success.
References BEM3D_IS_MESH, and bem3d_mesh_foreach_node().