Quadrature rules
Data Structures
struct BEM3DQuadratureSelector
struct BEM3DQuadratureRule
struct BEM3DQuadratureRuleFunc
Functions
BEM3DQuadratureRule * bem3d_quadrature_rule_new (gint n, gint nc)
gint bem3d_quadrature_rule_realloc (BEM3DQuadratureRule *q, gint n)
gint bem3d_quadrature_add_point (BEM3DQuadratureRule *q, gdouble xi, gdouble eta, gdouble w)
gdouble bem3d_quadrature_parameter (GtsPoint *p, BEM3DElement *e)
gint bem3d_quadrature_rule_default (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_kw (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_polar (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_polar_hs (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_wx (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_remap (gdouble xi0, gdouble eta0, gdouble xi1, gdouble eta1, gdouble xi2, gdouble eta2, gdouble s, gdouble t, gdouble w, gdouble *sn, gdouble *tn, gdouble *wn)
gint bem3d_quadrature_rule_write (BEM3DQuadratureRule *q, FILE *f)
gint bem3d_quadrature_rule_hayami (GtsPoint *xs, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_newman (GtsPoint *xs, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_newman_gradient (GtsPoint *xs, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_gauss (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
gint bem3d_quadrature_rule_series (GtsPoint *p, BEM3DElement *e, BEM3DQuadratureRule *q, BEM3DGreensFunction *gfunc, BEM3DParameters *param, gpointer data)
Detailed Description
Function Documentation
gint bem3d_quadrature_add_point (BEM3DQuadratureRule * q, gdouble xi, gdouble eta, gdouble w)
Add a new quadrature point to a rule
Parameters
q quadrature rule
xi area coordinate of quadrature point
eta area coordinate of quadrature point
w weight of quadrature point
Returns
::BEM3D_SUCCESS on success
gdouble bem3d_quadrature_parameter (GtsPoint * p, BEM3DElement * e)
Quadrature selection parameter used in choosing quadrature rules
Parameters
p field point
e element over which to integrate
Returns
sigma parameter.
References bem3d_element_corner, bem3d_element_vertex, and bem3d_element_vertex_number.
Referenced by bem3d_quadrature_rule_default().
gint bem3d_quadrature_rule_default (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Set quadrature rule to default
Parameters
p field point;
e element to integrate over;
q quadrature rule;
gfunc ignored;
param ignored;
data ignored.
Returns
::BEM3D_SUCCESS on success.
References bem3d_quadrature_parameter(), and bem3d_quadrature_select().
Referenced by bem3d_configuration_new().
gint bem3d_quadrature_rule_gauss (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Standard Gaussian quadrature for triangular elements
Parameters
p field point (ignored)
e element to integrate over
q quadrature rule to fill
gfunc ignored;
param ignored;
data pointer to gint containing the number of points in rule (1, 3, 4, or 7)
Returns
::BEM3D_SUCCESS on success, exit with error if number of points in rule is not 1, 3, 4, or 7.
References bem3d_element_corner_number, and bem3d_quadrature_rule_realloc().
gint bem3d_quadrature_rule_hayami (GtsPoint * xs, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Quadrature rule for near-singular integrals, using the method of Hayami, Ken, `Variable transformations for nearly singular integrals in the boundary element method', Publ. RIMS, Kyoto Univ., 41:821--842, 2005 and Hayami, Ken & Matsumoto, Hideki, `A numerical quadrature for nearly singular boundary element integrals', Engineering Analysis with Boundary Elements, 13:143--154, 1994. The integration point xs may not lie on the element.
Parameters
xs field point;
e element to integrate over;
q quadrature rule to fill;
gfunc ignored;
param ignored;
data gint[2], first element number of quadrature points in radius; second element number of points in angle.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_corner, bem3d_element_corner_index, bem3d_element_corner_number, bem3d_element_nearest_point(), bem3d_element_position(), bem3d_element_shape_func, bem3d_element_vertex, bem3d_element_vertex_eta, bem3d_element_vertex_xi, bem3d_quadrature_rule_realloc(), bem3d_shfunc_q1(), and bem3d_shfunc_t1().
gint bem3d_quadrature_rule_kw (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Khayat-Wilton quadrature rule for singular and near-singular integrals on triangular elements (Khayat, Michael A. and Wilton, Donald R., `Numerical evaluation of singular and near-singular potential integrals', IEEE Transactions on Antennas and Propagation, 53(10):3180--3190, 2005, doi: 10.1109/TAP.2005.856342
Parameters
p field point
e element to integrate over
q quadrature rule to fill
gfunc ignored;
param ignored;
data gint[2], first element number of quadrature points in radius; second element number of points in angle
Returns
::BEM3D_SUCCESS on success
References bem3d_area_coordinates_tri(), bem3d_element_corner, bem3d_element_corner_number, and bem3d_quadrature_rule_realloc().
BEM3DQuadratureRule* bem3d_quadrature_rule_new (gint n, gint nc)
Allocate a new quadrature rule
Parameters
n maximum number of points in quadrature rule;
nc number of components in integral.
Returns
pointer to new quadrature rule
Referenced by bem3d_element_area(), bem3d_reduction_func_int(), and bem3d_workspace_new().
gint bem3d_quadrature_rule_newman (GtsPoint * xs, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Generate a quadrature rule for linear elements (triangular for now) using the method of Newman, J. N., `Distributions of sources and normal dipoles over a quadrilateral panel', Journal of Engineering Mathematics, 20:113--126, 1986. The quadrature gives the weights for integration of the Laplace Green's function in the BEM3DQuadratureRule free terms so that, for example, $\int L_{i}/4\pi R\mathrm{d}S = f_{i}$, with $f_{i}$ the $i$th quadrature free term.
Parameters
xs field point for the integration;
e element for integration;
q quadrature rule;
gfunc this should contain bem3d_greens_func_laplace or NULL;
param ignored;
data ignored.
Returns
BEM3D_SUCCESS on success.
References bem3d_element_moment, bem3d_element_moment_order, bem3d_element_node, bem3d_element_node_number, bem3d_element_vertex, bem3d_greens_func_laplace(), bem3d_greens_function_func, and bem3d_greens_function_is_real.
gint bem3d_quadrature_rule_newman_gradient (GtsPoint * xs, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Generate a quadrature rule for gradient of potential field using linear elements (triangular for now) using the method of Newman, J. N., `Distributions of sources and normal dipoles over a quadrilateral panel', Journal of Engineering Mathematics, 20:113--126, 1986. The quadrature gives the weights for integration of the Laplace Green's function in the BEM3DQuadratureRule free terms so that, for example, $\nabla\int L_{i}/4\pi R\mathrm{d}S = f_{i}$, with $f_{i}$ the $i$th quadrature free term. The ordering of the free terms $g_{i}$ is such that $\int G \phi\mathrm{d}S=\sum_{i=0}^{2}g_{i}\phi_{i}$, $\frac{\partial}{\partial x}\int G \phi\mathrm{d}S=\sum_{i=3}^{5}g_{i}\phi_{i}$, $\frac{\partial}{\partial y}\int G \phi\mathrm{d}S=\sum_{i=6}^{8}g_{i}\phi_{i}$, and $\frac{\partial}{\partial z}\int G \phi\mathrm{d}S=\sum_{i=9}^{11}g_{i}\phi_{i}$, and likewise for the double layer term.
Parameters
xs field point for the integration;
e element for integration;
q quadrature rule;
gfunc this should contain bem3d_greens_func_laplace or NULL;
param ignored;
data ignored.
Returns
BEM3D_SUCCESS on success.
References bem3d_element_node, bem3d_element_node_number, bem3d_element_vertex, bem3d_greens_func_laplace(), bem3d_greens_function_func, and bem3d_greens_function_is_real.
gint bem3d_quadrature_rule_polar (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Polar transformation quadrature rule for singular and near-singular integrals on triangular elements.
Parameters
p field point;
e element to integrate over;
q quadrature rule to fill;
gfunc ignored;
param ignored;
data gint[2], first element number of quadrature points in radius; second element number of points in angle.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_corner_index, bem3d_element_corner_number, bem3d_element_nearest_point(), bem3d_element_vertex_eta, bem3d_element_vertex_number, bem3d_element_vertex_xi, and bem3d_quadrature_rule_realloc().
Referenced by bem3d_quadrature_rule_series(), and bem3d_quadrature_selector_default().
gint bem3d_quadrature_rule_polar_hs (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Polar transformation quadrature rule for hypersingular.
Parameters
p field point;
e element to integrate over;
q quadrature rule to fill;
gfunc ignored;
param ignored;
data gint[2], first element number of quadrature points in radius; second element number of points in angle.
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_corner_index, bem3d_element_corner_number, bem3d_element_nearest_point(), bem3d_element_vertex_eta, bem3d_element_vertex_number, bem3d_element_vertex_xi, and bem3d_quadrature_rule_realloc().
gint bem3d_quadrature_rule_realloc (BEM3DQuadratureRule * q, gint n)
Reallocate a quadrature rule to hold a new number of quadrature points. Note that the previous data in the rule are lost.
Parameters
q quadrature rule to reallocate
n number of points in reallocated rule
Returns
::BEM3D_SUCCESS on success
Referenced by bem3d_quadrature_rule_gauss(), bem3d_quadrature_rule_hayami(), bem3d_quadrature_rule_kw(), bem3d_quadrature_rule_polar(), bem3d_quadrature_rule_polar_hs(), and bem3d_quadrature_rule_wx().
gint bem3d_quadrature_rule_remap (gdouble xi0, gdouble eta0, gdouble xi1, gdouble eta1, gdouble xi2, gdouble eta2, gdouble s, gdouble t, gdouble w, gdouble * sn, gdouble * tn, gdouble * wn)
Remap a node and weight of a quadrature rule to a new base triangle. The main use for the function is in the decomposition of elements into triangles and the remapping of those triangles to the original element.
Parameters
xi0 coordinate of first corner of triangle;
eta0 coordinate of first corner of triangle;
xi1 coordinate of second corner of triangle;
eta1 coordinate of second corner of triangle;
xi2 coordinate of third corner of triangle;
eta2 coordinate of third corner of triangle;
s coordinate to remap;
t coordinate to remap;
w weight of node;
sn on exit, remapped coordinate;
tn on exit, remapped coordinate;
wn on exit, new weight of node.
Returns
::BEM3D_SUCCESS on success.
gint bem3d_quadrature_rule_series (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Semi-analytical series expansion for Helmholtz potential
Parameters
p field point
e element to integrate over
q quadrature rule to fill
gfunc ignored;
param ignored;
data pointer ignored.
Returns
::BEM3D_SUCCESS on success
References bem3d_element_find_node(), bem3d_element_node_number, bem3d_element_vertex, bem3d_element_vertex_number, bem3d_greens_func_helmholtz(), bem3d_greens_func_helmholtz_hs(), bem3d_greens_func_laplace(), bem3d_greens_function_func, bem3d_greens_function_is_real, bem3d_parameters_lambda_imag, bem3d_parameters_lambda_real, bem3d_parameters_wavenumber, bem3d_quadrature_rule_polar(), and bem3d_quadrature_rule_wx().
gint bem3d_quadrature_rule_write (BEM3DQuadratureRule * q, FILE * f)
Write the nodes and weights of a BEM3DQuadratureRule to a file, mainly of use in debugging.
Parameters
q BEM3DQuadratureRule to write;
f file pointer.
Returns
::BEM3D_SUCCESS on success.
gint bem3d_quadrature_rule_wx (GtsPoint * p, BEM3DElement * e, BEM3DQuadratureRule * q, BEM3DGreensFunction * gfunc, BEM3DParameters * param, gpointer data)
Symmetric Gaussian quadrature rules for triangles, taken from Wandzura, S. and Xiao, H., `Symmetric quadrature rules on a triangle', Computers and Mathematics with Applications, 45:1829--1840. If the element e is triangular, the rules are passed unmodified; if the element has more than three corners, the rules are mapped on to subtriangles formed by the element corners and the centroid of the element in intrinsic coordinates.
Parameters
p field point (ignored);
e element to integrate over;
q quadrature rule to fill;
gfunc ignored;
param ignored;
data gint *, number of points in rule (7, 25, 54, 85, 126, 175).
Returns
::BEM3D_SUCCESS on success.
References bem3d_element_corner_index, bem3d_element_corner_number, bem3d_element_vertex_eta, bem3d_element_vertex_xi, and bem3d_quadrature_rule_realloc().
Referenced by bem3d_element_area(), bem3d_quadrature_rule_series(), and bem3d_quadrature_selector_default().