Functions for data reduction
Functions
gint bem3d_reduction_func_max (BEM3DMesh *m, BEM3DMeshData *f, gint *idata, gint *ni, gdouble *ddata, gint *nd, gpointer data)
gint bem3d_reduction_func_min (BEM3DMesh *m, BEM3DMeshData *f, gint *idata, gint *ni, gdouble *ddata, gint *nd, gpointer data)
gint bem3d_reduction_func_sum (BEM3DMesh *m, BEM3DMeshData *f, gint *idata, gint *ni, gdouble *ddata, gint *nd, gpointer data)
gint bem3d_reduction_func_int (BEM3DMesh *m, BEM3DMeshData *f, gint *idata, gint *ni, gdouble *ddata, gint *nd, gpointer data)
gint bem3d_reduction_func_apply (gchar *func, BEM3DMesh *m, BEM3DMeshData *f, gint *idata, gint *ni, gdouble *ddata, gint *nd, gpointer data)
gchar * bem3d_reduction_func_description (gchar *str)
gint bem3d_reduction_func_list (FILE *output, gchar *format, gboolean describe)
Detailed Description
Function Documentation
bem3d_reduction_func_apply()
gint bem3d_reduction_func_apply (gchar * func, BEM3DMesh * m, BEM3DMeshData * f, gint * idata, gint * ni, gdouble * ddata, gint * nd, gpointer data)
Apply a named reduction operation to a BEM3DMeshData on a BEM3DMesh. Reduction operations can be listed by calling bem3d_reduction_func_list.
Parameters
func the name of reduction operation
m a BEM3DMesh
f a BEM3DMeshData containing data for m
idata array containing integer data on exit
ni number of entries in idata on exit
ddata array containing double precision data on exit
nd number of entries in ddata on exit
data ignored
Returns
0 on success
bem3d_reduction_func_description()
gchar* bem3d_reduction_func_description (gchar * str)
Short description of a reduction operation.
Parameters
str the name of the reduction operation, e.g. `max'
Returns
a pointer to a string containing a description of the operation, or NULL if not found.
bem3d_reduction_func_int()
gint bem3d_reduction_func_int (BEM3DMesh * m, BEM3DMeshData * f, gint * idata, gint * ni, gdouble * ddata, gint * nd, gpointer data)
Surface integral of data
Parameters
m a BEM3DMesh
f a BEM3DMeshData containing data for m
idata ignored
ni ignored
ddata surface integral on m of data in each column of f
nd on exit 1
data ignored
Returns
0 on success
References bem3d_mesh_foreach_element(), and bem3d_quadrature_rule_new().
bem3d_reduction_func_list()
gint bem3d_reduction_func_list (FILE * output, gchar * format, gboolean describe)
Write a list of available reduction operations.
Parameters
output a FILE stream to write information to;
format a `printf' format string for the data;
describe if TRUE, also write the short description of the reduction operation
The format string should be appropriate to the setting of describe. If describe is FALSE, format should contain one entry of `s' (for the name of the operation); if TRUE, format should contain `s' twice (one for the name of the operation and one for its description).
Returns
0 on success
bem3d_reduction_func_max()
gint bem3d_reduction_func_max (BEM3DMesh * m, BEM3DMeshData * f, gint * idata, gint * ni, gdouble * ddata, gint * nd, gpointer data)
Maximum value of entries in each column of data
Parameters
m a BEM3DMesh
f a BEM3DMeshData containing data for m
idata on exit, index of maximum value in each column
ni on exit 1
ddata maximum value in each column of f
nd on exit 1
data ignored
Returns
0 on success
References bem3d_mesh_data_get(), and bem3d_mesh_node_number().
bem3d_reduction_func_min()
gint bem3d_reduction_func_min (BEM3DMesh * m, BEM3DMeshData * f, gint * idata, gint * ni, gdouble * ddata, gint * nd, gpointer data)
Minimum value of entries in each column of data
Parameters
m a BEM3DMesh
f a BEM3DMeshData containing data for m
idata on exit, index of minimum value in each column
ni on exit 1
ddata minimum value in each column of f
nd on exit 1
data ignored
Returns
0 on success
References bem3d_mesh_data_get(), and bem3d_mesh_node_number().
bem3d_reduction_func_sum()
gint bem3d_reduction_func_sum (BEM3DMesh * m, BEM3DMeshData * f, gint * idata, gint * ni, gdouble * ddata, gint * nd, gpointer data)
Sum of entries in each column
Parameters
m a BEM3DMesh
f a BEM3DMeshData containing data for m
idata ignored
ni ignored
ddata sum of entries in each column of f
nd on exit 1
data ignored
Returns
0 on success
References bem3d_mesh_data_get(), and bem3d_mesh_node_number().