Shape functions
Typedefs
typedef gint(* BEM3DShapeFunc) (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
Functions
gint bem3d_shfunc_t0 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shfunc_t1 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shfunc_t2 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shfunc_t3 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shfunc_q1 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shfunc_q2 (gdouble s, gdouble t, gdouble *L, gdouble *dLds, gdouble *dLdt, gpointer data)
gint bem3d_shapefunc_lookup_add (BEM3DShapeFunc func, gchar *name)
gint bem3d_shapefunc_lookup_init ()
BEM3DShapeFunc bem3d_shapefunc_lookup_func (const gchar *name)
const gchar * bem3d_shapefunc_lookup_name (BEM3DShapeFunc func)
Detailed Description
Shape functions for triangular and quadrilateral elements, mainly taken from the FEMPACK library of John Burkardt:
http://www.csit.fsu.edu/~burkardt/m_src/fempack/fempack.html http://orion.math.iastate.edu/burkardt/f_src/fempack/fempack.htm
Shape functions are called with the arguments s and t and return the shape functions and derivatives in arrays which must be properly allocated by the user before the function call. User-defined shape functions can be used but must be of the BEM3DShapeFunc type. They must also be added to the internal lookup table, using bem3d_shapefunc_lookup_add before any elements using them can be read.
For mathematical validity and in order for other functions in the library to work, the shape functions should meet the requirements of `Shape function magic', http://caswww.colorado.edu/courses.d/IFEM.d/IFEM.Ch18.d/IFEM.Ch18.pdf
The definition of BEM3DShapeFunc has provision for passing data to the shape function. Within bem3dlib, at present, all calls set the data field to NULL. This behaviour will not change for the isoparametric elements which are currently implemented but may be modified in future to take data from the element.
Typedef Documentation
BEM3DShapeFunc
BEM3D shape function definition
Parameters
s local coordinate
t local coordinate
L array to be filled with the shape function(s) at (s,t)
dLds array to be filled with the derivatives of L at (s,t)
dLdt array to be filled with the derivatives of L at (s,t)
data data to be passed to the shape function
Returns
0 on success
Function Documentation
gint bem3d_shapefunc_lookup_add (BEM3DShapeFunc func, gchar * name)
Add a BEM3DShapeFunc to the lookup table used in mapping shape functions to names.
Parameters
func BEM3DShapeFunc to add
name name of shape function, which must be unique.
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_shapefunc_lookup_init().
BEM3DShapeFunc bem3d_shapefunc_lookup_func (const gchar * name)
Look up a shape function, given its name.
Parameters
name the name under which the shape function has been registered.
Returns
the BEM3DShapeFunc of that name. Otherwise, the program reports an error and exits.
Referenced by bem3d_mesh_read().
gint bem3d_shapefunc_lookup_init (void)
Initialize the shape function lookup table. This function must be called before any shape functions are used or elements read. As well as allocating the lookup table, it also adds the basic isoparametric shape functions of order 0--3 for triangles and orders 1 and 2 for quadrilaterals.
Returns
::BEM3D_SUCCESS on success.
References bem3d_shapefunc_lookup_add(), bem3d_shfunc_q1(), bem3d_shfunc_q2(), bem3d_shfunc_t0(), bem3d_shfunc_t1(), bem3d_shfunc_t2(), and bem3d_shfunc_t3().
const gchar* bem3d_shapefunc_lookup_name (BEM3DShapeFunc func)
Find the name under which a BEM3DShapeFunc has been registered.
Parameters
func a BEM3DShapeFunc
Returns
the name of func in the lookup table, or NULL if not found.
Referenced by bem3d_element_write().
gint bem3d_shfunc_q1 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Linear shape function for a quadrilateral $(0,0)$, $(1,0)$, $(1,1)$, $(0,1)$.
Parameters
s local coordinate
t local coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_element_build_q1(), bem3d_quadrature_rule_hayami(), and bem3d_shapefunc_lookup_init().
gint bem3d_shfunc_q2 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Second order shape function for a quadrilateral $(0,0)$, $(1,0)$, $(1,1)$, $(0,1)$.
Parameters
s local coordinate
t local coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_element_build_q2(), and bem3d_shapefunc_lookup_init().
gint bem3d_shfunc_t0 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Zero order (constant) shape function for a triangle, $L=1$.
Parameters
s coordinate
t coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success
Referenced by bem3d_element_build_t0(), and bem3d_shapefunc_lookup_init().
gint bem3d_shfunc_t1 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Linear shape function for a triangle $(0,0)$, $(1,0)$, $(0,1)$.
Parameters
s local coordinate
t local coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_element_build_t0(), bem3d_element_build_t1(), bem3d_quadrature_rule_hayami(), and bem3d_shapefunc_lookup_init().
gint bem3d_shfunc_t2 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Second order shape function for a triangle $(0,0)$, $(1,0)$, $(0,1)$.
Parameters
s local coordinate
t local coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_element_build_t2(), and bem3d_shapefunc_lookup_init().
gint bem3d_shfunc_t3 (gdouble s, gdouble t, gdouble * L, gdouble * dLds, gdouble * dLdt, gpointer data)
Third order shape function for a triangle $(0,0)$, $(1,0)$, $(0,1)$.
Parameters
s local coordinate
t local coordinate
L $L_{i}$, shape functions;
dLds derivatives of $L_{i}$ with respect to $s$;
dLdt derivatives of $L_{i}$ with respect to $t$;
data data to be passed to the shape function (ignored)
Returns
::BEM3D_SUCCESS on success.
Referenced by bem3d_element_build_t3(), and bem3d_shapefunc_lookup_init().