Data on BEM3D surfaces
Functions
 BEM3DMeshData * bem3d_mesh_data_new (BEM3DMesh *m, gint n)
gint bem3d_mesh_data_free (BEM3DMeshData *d)
 BEM3DMeshData * bem3d_mesh_data_sized_new (gint n, gint m)
gint bem3d_mesh_data_clear (BEM3DMeshData *m)
gdouble * bem3d_mesh_data_get (BEM3DMeshData *m, gint i)
gint bem3d_mesh_data_add (BEM3DMeshData *f, gint i, GArray *g)
gint bem3d_mesh_data_write (BEM3DMeshData *f, FILE *fp, gchar *header)
gint bem3d_mesh_data_read (BEM3DMeshData **f, FILE *fp, gint width)
gint bem3d_mesh_data_add_node (BEM3DMeshData *m, gint i)
gint bem3d_mesh_data_multiproc_sum (BEM3DMeshData *m)
gint bem3d_mesh_data_node_number (BEM3DMeshData *d)
 BEM3DMeshData * bem3d_mesh_data_merge (BEM3DMeshData *f1, BEM3DMeshData *f2, gboolean strict)
gint bem3d_mesh_data_add_mesh (BEM3DMeshData *d, BEM3DMesh *m)
gint bem3d_mesh_data_write_weights (BEM3DMeshData *f, FILE *fp, gint *fields, gint nfields)
Detailed Description
Function Documentation
bem3d_mesh_data_add()
gint bem3d_mesh_data_add (BEM3DMeshData * f, gint i, GArray * g)
Add an array of data to a mesh data entry.
Parameters
f BEM3DMeshData block;
i global node index;
g array of entries to add to field i.
Returns
0 on success
References bem3d_mesh_data_get().
bem3d_mesh_data_add_mesh()
gint bem3d_mesh_data_add_mesh (BEM3DMeshData * d, BEM3DMesh * m)
Expand a BEM3DMeshData to include entries for another mesh, so that the data block contains data for more than one mesh.
Parameters
d an existing BEM3DMeshData
m a BEM3DMesh whose nodes are to be added to d
Returns
0 on success
References bem3d_mesh_foreach_node().
bem3d_mesh_data_add_node()
gint bem3d_mesh_data_add_node (BEM3DMeshData * m, gint i)
Add a node to a BEM3DMeshData.
Parameters
m mesh data block to add information to;
i index of node to add. A check is performed to ensure that it is not already present.
Returns
0 on success.
References bem3d_mesh_data_get().
bem3d_mesh_data_clear()
gint bem3d_mesh_data_clear (BEM3DMeshData * m)
Set all entries of a BEM3DMeshData block to zero.
Parameters
m BEM3DMeshData to clear.
Returns
0 on success
bem3d_mesh_data_free()
gint bem3d_mesh_data_free (BEM3DMeshData * d)
Free a BEM3DMeshData.
Parameters
d BEM3DMeshData to be freed.
Returns
BEM3D_SUCCESS on success ;
bem3d_mesh_data_get()
gdouble* bem3d_mesh_data_get (BEM3DMeshData * m, gint i)
Look up the data for a given mesh node.
Parameters
m BEM3DMeshData block;
i global index of node to look up.
Returns
a pointer to the data for node i, NULL if the index is not in the block.
Referenced by bem3d_gmsh_write_element(), bem3d_mesh_data_add(), bem3d_mesh_data_add_node(), and bem3d_reduction_func_sum().
bem3d_mesh_data_merge()
 BEM3DMeshData* bem3d_mesh_data_merge (BEM3DMeshData * f1, BEM3DMeshData * f2, gboolean strict)
Merge two data blocks into a single block. This is intended for merging data generated for two disjoint meshes, with different indices. If an index appears in both blocks the behaviour is undefined. The output block will be sized to accomodate all data from both inputs, with zero padding where required.
Parameters
f1 an input BEM3DMeshData;
f2 another input BEM3DMeshData;
strict (not currently used).
Returns
a new BEM3DMeshData containing the data from f1 and f2.
References bem3d_mesh_data_node_number(), and bem3d_mesh_data_sized_new().
bem3d_mesh_data_multiproc_sum()
gint bem3d_mesh_data_multiproc_sum (BEM3DMeshData * m)
Sum the data stored in a BEM3DMeshData block across all processes so that each process holds the same data.
Parameters
m BEM3DMeshData block to sum
Returns
0 on success.
bem3d_mesh_data_new()
 BEM3DMeshData* bem3d_mesh_data_new (BEM3DMesh * m, gint n)
Allocate a BEM3DMeshData block, sized to the number of collocation points on a BEM3DMesh.
Parameters
m BEM3DMesh for which to allocate data
n number of data points per mesh node
Returns
pointer to new data block
References BEM3D_IS_MESH, bem3d_mesh_data_sized_new(), bem3d_mesh_foreach_node(), bem3d_mesh_node_index_max, bem3d_mesh_node_index_min, and bem3d_mesh_node_number().
bem3d_mesh_data_node_number()
gint bem3d_mesh_data_node_number (BEM3DMeshData * d)
Find the number of nodes in a BEM3DMeshData.
Parameters
d a BEM3DMeshData.
Returns
the number of nodes in d, or zero if d is NULL.
Referenced by bem3d_mesh_data_merge(), and bem3d_reduction_func_sum().
bem3d_mesh_data_read()
gint bem3d_mesh_data_read (BEM3DMeshData ** f, FILE * fp, gint width)
Read a BEM3DMeshData block from an input file, allocating it as necessary.
Parameters
f ::BEM3DMEshData block to allocate;
fp input file stream;
width data is set to the maximum of width and the number of elements specified in the input file; set to 0 to use the number specified in the file.
Returns
0 on success.
References bem3d_mesh_data_sized_new().
bem3d_mesh_data_sized_new()
 BEM3DMeshData* bem3d_mesh_data_sized_new (gint n, gint m)
Allocate BEM3DMeshData block of a given size, without linking to a BEM3DMesh.
Parameters
n number of data points per mesh node;
m number of points for which to allocate the BEM3DMeshData.
Returns
BEM3DMeshData block.
Referenced by bem3d_mesh_data_merge(), bem3d_mesh_data_new(), and bem3d_mesh_data_read().
bem3d_mesh_data_write()
gint bem3d_mesh_data_write (BEM3DMeshData * f, FILE * fp, gchar * header)
Write a BEM3DMeshData block to a file. The output format is one line containing:
NP NE BEM3DMeshData
where NP is the number of nodes in the block and NE is the number of numerical entries per point, followed by NP lines each containing NE numerical entries. If header is not NULL, it is used in place of the standard first line. If it contains C formatting strings d, these generate NP and NE.
Parameters
f BEM3DMeshData block;
fp file pointer;
header first line of output file (may be NULL)
Returns
0 on success.
bem3d_mesh_data_write_weights()
gint bem3d_mesh_data_write_weights (BEM3DMeshData * f, FILE * fp, gint * fields, gint nfields)
Write a block of data in the form of a single row suitable for use in a weighting matrix, e.g. of a type generated by bem3d_function_integral_weights. Data are written on one row in the form
index f0 f1 f2 index f0 f1 f2 ...
with any entries with all data equal to zero neglected, effectively treating the data as a sparse matrix.
Parameters
f data to write;
fp file pointer for output;
fields indices of fields to write to output (must all be less than the number of fields per node in f);
nfields number of fields to write.
Returns
0 on success