Quadrature selection
Functions
 BEM3DQuadratureSelector * bem3d_quadrature_selector_new (void)
gint bem3d_quadrature_selector_clear (BEM3DQuadratureSelector *s)
gint bem3d_quadrature_selector_add (BEM3DQuadratureSelector *s, BEM3DQuadratureRuleFunc f, gdouble p, gint N, gint M)
gint bem3d_quadrature_select (BEM3DQuadratureSelector *s, gdouble p, BEM3DQuadratureRuleFunc *f, gpointer *data)
 BEM3DQuadratureSelector * bem3d_quadrature_selector_default ()
Detailed Description
BEM3D has a built-in method for selecting quadrature rules (which can be overridden using a configuration file . The selection is performed using a parameter $\sigma$, calculated from geometrical properties of the element, and of the point. For an element, define $\mathbf{c}=\overline{\mathbf{x}_{i}}$, the mean of the element vertices. Then $R_{s}$ is defined as the maximum value of $\sqrt{2}|\mathbf{c}-\mathbf{x}_{i}|$, so that a sphere containing the element is defined. The point-element distance is defined as $R_{p}=|\mathbf{c}-\mathbf{x}|$. For field points which coincide with an element vertex $\sigma=0$. For $R_{p}<R_{s}$, $\sigma=z_{n}/R_{s}$ where $z_{n}$ is the approximate normal distance from the field point to the plane of the element. For $R_{p}\geq R_{s}$, $\sigma=R_{p}/R_{s}$.
Function Documentation
bem3d_quadrature_select()
gint bem3d_quadrature_select (BEM3DQuadratureSelector * s, gdouble p, BEM3DQuadratureRuleFunc * f, gpointer * data)
Select a quadrature for a given parameter
Parameters
s BEM3DQuadratureSelector
p quadrature parameter, returned by bem3d_quadrature_parameter
f BEM3DQuadratureRuleFunc to call
data to pass to f
Returns
Referenced by bem3d_quadrature_rule_default().
bem3d_quadrature_selector_add()
gint bem3d_quadrature_selector_add (BEM3DQuadratureSelector * s, BEM3DQuadratureRuleFunc f, gdouble p, gint N, gint M)
Add a new quadrature to a selection rule
Parameters
s BEM3DQuadratureSelector;
f BEM3DQuadratureRuleFunc to add.
p parameter, the quadrature will be selected if bem3d_quadrature_parameter returns a value greater than p
N number of points in angle in polar rules
M number of points in radius in polar rules
N and M can be used for different purposes in other rules, but will always be passed as an array of int of length 2, [N M]
Returns
0 on success
Referenced by bem3d_quadrature_selector_default().
bem3d_quadrature_selector_clear()
gint bem3d_quadrature_selector_clear (BEM3DQuadratureSelector * s)
Clear a quadrature selection rule
Parameters
s quadrature selector
Returns
0 on success
bem3d_quadrature_selector_default()
 BEM3DQuadratureSelector* bem3d_quadrature_selector_default (void)
Default quadrature selection rule which is reasonably good for most problems. For points close to, or on, an element, polar or Hayami's PART quadrature is used, switching to a symmetric high-order rule further away.
Returns
pointer to quadrature selector
References bem3d_quadrature_rule_polar(), bem3d_quadrature_rule_wx(), bem3d_quadrature_selector_add(), and bem3d_quadrature_selector_new().
Referenced by bem3d_configuration_new().
bem3d_quadrature_selector_new()
 BEM3DQuadratureSelector* bem3d_quadrature_selector_new (void)
Allocate a new BEM3DQuadratureSelector
Returns
pointer to new selector
Referenced by bem3d_quadrature_selector_default().