Mesh skeletons
Functions
 BEM3DMeshSkeleton * bem3d_mesh_skeleton_new (BEM3DMesh *m, gint order_max)
gint bem3d_mesh_skeleton_init (BEM3DMeshSkeleton *s, BEM3DQuadratureRule *q, BEM3DAverage anorm)
gint bem3d_mesh_skeleton_write (BEM3DMeshSkeleton *s, FILE *f)
Detailed Description
BEM3D skeletons are representations of meshes as arrays of point sources, mainly intended for use in interfacing to third-party libraries such as Fast Multipole Methods which take input as a set of elementary sources.
Function Documentation
bem3d_mesh_skeleton_init()
gint bem3d_mesh_skeleton_init (BEM3DMeshSkeleton * s, BEM3DQuadratureRule * q, BEM3DAverage anorm)
Initialize a BEM3DMeshSkeleton which has been allocated with bem3d_mesh_skeleton_new. You should be careful to use a BEM3DQuadratureRule which guarantees source points which are distinct from the collocation points. For example, a three-point Gaussian quadrature with nodes at the midpoints of triangle edges will generate source points which coincide with the mid-edge nodes of a second-order triangular element.
Parameters
s a BEM3DMeshSkeleton
q a BEM3DQuadratureRule used to find points on mesh elements
anorm a BEM3DAverage specification used in computing collocation point normals
Returns
BEM3D_SUCCESS on success
References bem3d_mesh_element_number, bem3d_mesh_foreach_element(), and bem3d_mesh_node_number().
bem3d_mesh_skeleton_new()
 BEM3DMeshSkeleton* bem3d_mesh_skeleton_new (BEM3DMesh * m, gint order_max)
Allocate a new BEM3DMeshSkeleton for a given mesh
Parameters
m a BEM3DMesh
order_max maximum number of source points per element on the skeleton
Returns
a new BEM3DMeshSkeleton on success.
References bem3d_mesh_element_node_number_max(), bem3d_mesh_element_number, bem3d_mesh_index_range(), and bem3d_mesh_node_number().
bem3d_mesh_skeleton_write()
gint bem3d_mesh_skeleton_write (BEM3DMeshSkeleton * s, FILE * f)
Write a BEM3DMeshSkeleton to file
Parameters
s a BEM3DMeshSkeleton
f FILE pointer
Returns
BEM3D_SUCCESS on success