Computing fields
Functions
gint bem3d_radiation_func_laplace (GArray *G, GArray *dG, GArray *phi, GArray *dphi, GArray *f, gpointer data)
gint bem3d_radiation_func_helmholtz (GArray *G, GArray *dG, GArray *phi, GArray *dphi, GArray *f, gpointer data)
gint bem3d_mesh_radiation_point (BEM3DMesh *m, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DLookupFunc lf, gpointer ldata, GtsPoint *x, GArray *f, BEM3DWorkspace *work)
gint bem3d_element_radiation_point (BEM3DElement *e, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DLookupFunc lfunc, gpointer ldata, GtsPoint *x, GArray *G, GArray *dGdn, GArray *phi, GArray *dphi, BEM3DWorkspace *work)
gint bem3d_mesh_radiation_mesh (BEM3DMesh *m, BEM3DConfiguration *config, BEM3DParameters *gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DMesh *s, BEM3DMeshData *f, BEM3DWorkspace *work)
Detailed Description
Function Documentation
gint bem3d_element_radiation_point (BEM3DElement * e, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DLookupFunc lfunc, gpointer ldata, GtsPoint * x, GArray * G, GArray * dGdn, GArray * phi, GArray * dphi, BEM3DWorkspace * work)
Compute the field radiated to a point from a BEM3DElement with known solution
Parameters
e BEM3DElement
config BEM3DConfiguration for problem;
gdata BEM3DParameters to pass to Green's function;
lfunc lookup function for solution
ldata user data to pass to lf
x field point
G integral of Green's function
dGdn integral of Green's function normal derivative
phi solution at element nodes
dphi solution normal derivative at element nodes
work a BEM3DWorkspace
Returns
0 on success
References bem3d_element_global_index, bem3d_element_node_func, bem3d_element_node_number, bem3d_element_normal(), bem3d_element_position(), bem3d_element_shape_func, bem3d_greens_function_component_number, bem3d_greens_function_func, and bem3d_greens_function_is_real.
gint bem3d_mesh_radiation_mesh (BEM3DMesh * m, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DLookupFunc lfunc, gpointer ldata, BEM3DMesh * s, BEM3DMeshData * f, BEM3DWorkspace * work)
Compute the field radiated to a BEM3DMesh from a BEM3DMesh with known solution
Parameters
m BEM3DMesh for geometry;
config BEM3DConfiguration for problem;
gdata BEM3DParameters to pass to Green's function;
lfunc lookup function for solution
ldata user data to pass to lfunc
s BEM3DMesh on which to compute field
f BEM3DMeshData block containing computed field
work a BEM3DWorkspace
Returns
0 on success
References BEM3D_IS_MESH, bem3d_mesh_foreach_node(), bem3d_mesh_node_index_max, and bem3d_mesh_node_index_min.
gint bem3d_mesh_radiation_point (BEM3DMesh * m, BEM3DConfiguration * config, BEM3DParameters * gdata, BEM3DLookupFunc lf, gpointer ldata, GtsPoint * x, GArray * f, BEM3DWorkspace * work)
Compute the field radiated to a point from a BEM3DMesh with known solution
Parameters
m BEM3DMesh for geometry;
config BEM3DConfiguration for problem;
gdata BEM3DParameters to pass to Green's function;
lf lookup function for solution
ldata user data to pass to lf
x field point
f radiated solution
work a BEM3DWorkspace
Returns
0 on success
References bem3d_greens_function_component_number, bem3d_greens_function_is_real, BEM3D_IS_MESH, bem3d_mesh_foreach_element(), bem3d_mesh_node_index_max, and bem3d_mesh_node_index_min.
gint bem3d_radiation_func_helmholtz (GArray * G, GArray * dG, GArray * phi, GArray * dphi, GArray * f, gpointer data)
Standard built-in radiation function for Helmholtz equation, which can be used for any complex problem
Parameters
G integral of Green's function
dG integral of normal derivative of Green's function
phi solution at nodes
dphi normal derivative of solution at nodes
f radiated solution integral of $Gd\phi/dn+dG/dn\phi$
data user data, ignored in this function
Returns
0 on success
gint bem3d_radiation_func_laplace (GArray * G, GArray * dG, GArray * phi, GArray * dphi, GArray * f, gpointer data)
Standard built-in radiation function for Laplace equation, which can be used for any real problem
Parameters
G integral of Green's function
dG integral of normal derivative of Green's function
phi solution at nodes
dphi normal derivative of solution at nodes
f radiated solution integral of $Gd\phi/dn+dG/dn\phi$
data user data, ignored in this function
Returns
0 on success