BEM3D edges
Data Structures
struct BEM3DEdgeClass
Functions
 BEM3DEdge * bem3d_edge_new (BEM3DEdgeClass *klass)
gint bem3d_mesh_vertex_index_number (BEM3DMesh *m, GtsVertex *v)
GSList * bem3d_mesh_sharp_vertices (BEM3DMesh *m)
GSList * bem3d_mesh_extract_edges (BEM3DMesh *m, GSList **e)
gint bem3d_edge_clear (BEM3DEdge *e)
gint bem3d_edge_copy (BEM3DEdge *e, BEM3DEdge *f)
gint bem3d_edge_write (BEM3DEdge *e, FILE *f)
guint bem3d_edge_read (BEM3DEdge *e, GtsFile *f)
gboolean bem3d_edge_is_oriented (BEM3DEdge *e, BEM3DMesh *m)
gint bem3d_invert_edge (BEM3DEdge *e)
Detailed Description
A data type and set of functions which allow the handling of edges, oriented lists of sharp nodes on a mesh.
Function Documentation
bem3d_edge_clear()
gint bem3d_edge_clear (BEM3DEdge * e)
Clear a BEM3DEdge, i.e. set its number of nodes to zero.
Parameters
e the BEM3DEdge to clear.
Returns
::BEM3D_SUCCESS on success.
bem3d_edge_copy()
gint bem3d_edge_copy (BEM3DEdge * e, BEM3DEdge * f)
Copy a BEM3DEdge. This is a `deep' copy, i.e. the GtsVertex at each node is copied into a new instance, rather than being linked to the same address, so that the copy can be swept without affecting the original points.
Parameters
e the destination BEM3DEdge;
f the source BEM3DEdge.
Returns
::BEM3D_SUCCESS on success.
bem3d_edge_is_oriented()
gboolean bem3d_edge_is_oriented (BEM3DEdge * e, BEM3DMesh * m)
Check if a BEM3DEdge is aligned with its parent BEM3DMesh, by comparing the direction of the edge with the corresponding edges on the mesh.
Parameters
e a BEM3DEdge;
m the parent BEM3DMesh of e.
Returns
TRUE if e is compatibly aligned with the sharp edges of m.
References bem3d_element_find_index(), bem3d_elements_from_vertices(), BEM3D_IS_MESH, and bem3d_mesh_node_from_index().
bem3d_edge_new()
 BEM3DEdge* bem3d_edge_new (BEM3DEdgeClass * klass)
Allocate a new BEM3DEdge.
Parameters
klass a BEM3DEdgeClass.
Returns
the newly allocated object.
bem3d_edge_read()
guint bem3d_edge_read (BEM3DEdge * e, GtsFile * f)
Read a BEM3DEdge from a file. The format is that used by bem3d_edge_write.
Parameters
e a BEM3DEdge to which the edge in f will be added;
f a ::GtsFile.
Returns
BEM3D_SUCCESS on success.
bem3d_edge_write()
gint bem3d_edge_write (BEM3DEdge * e, FILE * f)
Write a BEM3DEdge to a file. The output format is one line:
N BEM3DEdge
where N is the number of edge nodes followed by N pairs of indices, one pair per line.
Parameters
e the BEM3DEdge to write;
f the file stream to which e should be written.
Returns
BEM3D_SUCCESS on success.
bem3d_invert_edge()
gint bem3d_invert_edge (BEM3DEdge * e)
Invert a BEM3DEdge by swapping the upper and lower indices to properly align it with its parent BEM3DMesh.
Parameters
e a BEM3DEdge.
Returns
::BEM3D_SUCCESS on success.
bem3d_mesh_extract_edges()
GSList* bem3d_mesh_extract_edges (BEM3DMesh * m, GSList ** e)
Extract the edge connectivity data from a list of sharp nodes.
Parameters
m a BEM3DMesh;
e GSList of vertices of m which are sharp (from bem3d_mesh_sharp_vertices).
Returns
a GSList of BEM3DEdge, each of which is a connected, oriented edge on m.
References BEM3D_IS_MESH.
bem3d_mesh_sharp_vertices()
GSList* bem3d_mesh_sharp_vertices (BEM3DMesh * m)
Find the sharp nodes of a BEM3DMesh, i.e. those with multiple indices, as found by bem3d_mesh_vertex_index_number.
Parameters
m a BEM3DMesh.
Returns
a GSList of the GtsVertex's of m which have multiple indices.
References BEM3D_IS_MESH.
bem3d_mesh_vertex_index_number()
gint bem3d_mesh_vertex_index_number (BEM3DMesh * m, GtsVertex * v)
Find the number of indices assigned to a mesh vertex.
Parameters
m a BEM3DMesh;
v a GtsVertex forming part of m.
Returns
the number of indices used by v on m.
References bem3d_element_find_vertex(), bem3d_element_global_index, BEM3D_IS_MESH, and bem3d_mesh_vertex_elements().